### ISSUE TITLE
Roborock Adapter startet bei fehlender Internetverbindung immer wieder neu 

### ISSUE THREAD

**Issue by DonToben** [copystring/ioBroker.roborock#118]
Könntest du dir das bitte ansehen.
Gerade ein Update der Fritzbox gemacht. Danach hat iobroker den Roborock Adapter automatisch angehalten wegen zu vieler Neustarts. Passiert eigentlich immer nachdem die Internetverbindung eine Zeit nicht verfügbar ist. Andere Adapter haben das Problem nicht.
Kannst du dir das erklären?

-03-24 09:00:11.217 - warn: roborock.0 (29551) MQTT connection close.
2023-03-24 09:00:11.222 - warn: roborock.0 (29551) MQTT connection reconnect.
2023-03-24 12:00:11.212 - warn: roborock.0 (29551) MQTT connection close.
2023-03-24 12:00:11.213 - warn: roborock.0 (29551) MQTT connection reconnect.
2023-03-24 15:00:11.213 - warn: roborock.0 (29551) MQTT connection close.
2023-03-24 15:00:11.214 - warn: roborock.0 (29551) MQTT connection reconnect.
2023-03-24 16:33:11.623 - warn: roborock.0 (29551) State "roborock.0.Devices.5Im6TX0cm6mgxaWxHaEos7.consumables.carpet_clean_mode" has no existing object, this might lead to an error in future versions
2023-03-24 17:14:41.533 - error: roborock.0 (29551) MQTT connection offline: undefined
2023-03-24 17:14:41.534 - warn: roborock.0 (29551) MQTT connection close.
2023-03-24 17:14:42.534 - warn: roborock.0 (29551) MQTT connection reconnect.
2023-03-24 17:14:47.446 - error: roborock.0 (29551) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-03-24 17:14:47.447 - error: roborock.0 (29551) unhandled promise rejection: getaddrinfo EAI_AGAIN api-eu.roborock.com
2023-03-24 17:14:47.449 - error: roborock.0 (29551) Error: getaddrinfo EAI_AGAIN api-eu.roborock.com
at Function.AxiosError.from (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/dist/node/axios.cjs:825:14)
at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/dist/node/axios.cjs:2973:25)
at RedirectableRequest.emit (node:events:513:28)
at ClientRequest.eventHandlers. (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
at ClientRequest.emit (node:events:513:28)
at TLSSocket.socketErrorListener (node:_http_client:494:9)
at TLSSocket.emit (node:events:513:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-03-24 17:14:47.450 - error: roborock.0 (29551) Exception-Code: EAI_AGAIN: getaddrinfo EAI_AGAIN api-eu.roborock.com
2023-03-24 17:14:47.458 - info: roborock.0 (29551) terminating
2023-03-24 17:14:47.460 - warn: roborock.0 (29551) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-03-24 17:15:04.040 - error: host.raspberrypi instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-24 17:15:04.042 - info: host.raspberrypi Restart adapter system.adapter.roborock.0 because enabled
2023-03-24 17:15:05.269 - info: host.raspberrypi instance system.adapter.roborock.0 started with pid 24330
2023-03-24 17:15:08.304 - info: roborock.0 (24330) starting. Version 0.1.6 (non-npm: copystring/ioBroker.roborock) in /opt/iobroker/node_modules/iobroker.roborock, node: v16.19.0, js-controller: 4.0.24
2023-03-24 17:15:30.675 - error: roborock.0 (24330) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-03-24 17:15:30.677 - error: roborock.0 (24330) unhandled promise rejection: getaddrinfo ENOTFOUND euiot.roborock.com
2023-03-24 17:15:30.682 - error: roborock.0 (24330) Error: getaddrinfo ENOTFOUND euiot.roborock.com
at Function.AxiosError.from (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/dist/node/axios.cjs:825:14)
at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/dist/node/axios.cjs:2973:25)
at RedirectableRequest.emit (node:events:513:28)
at ClientRequest.eventHandlers. (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
at ClientRequest.emit (node:events:513:28)
at TLSSocket.socketErrorListener (node:_http_client:494:9)
at TLSSocket.emit (node:events:513:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-03-24 17:15:30.683 - error: roborock.0 (24330) Exception-Code: ENOTFOUND: getaddrinfo ENOTFOUND euiot.roborock.com
2023-03-24 17:15:30.694 - info: roborock.0 (24330) terminating
2023-03-24 17:15:30.697 - warn: roborock.0 (24330) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-03-24 17:15:31.326 - error: host.raspberrypi instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-24 17:15:31.327 - info: host.raspberrypi Restart adapter system.adapter.roborock.0 because enabled
2023-03-24 17:15:32.473 - info: host.raspberrypi instance system.adapter.roborock.0 started with pid 24384
2023-03-24 17:15:35.563 - info: roborock.0 (24384) starting. Version 0.1.6 (non-npm: copystring/ioBroker.roborock) in /opt/iobroker/node_modules/iobroker.roborock, node: v16.19.0, js-controller: 4.0.24
2023-03-24 17:15:55.287 - error: roborock.0 (24384) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-03-24 17:15:55.288 - error: roborock.0 (24384) unhandled promise rejection: getaddrinfo ENOTFOUND euiot.roborock.com
2023-03-24 17:15:55.290 - error: roborock.0 (24384) Error: getaddrinfo ENOTFOUND euiot.roborock.com
at Function.AxiosError.from (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/dist/node/axios.cjs:825:14)
at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/dist/node/axios.cjs:2973:25)
at RedirectableRequest.emit (node:events:513:28)
at ClientRequest.eventHandlers. (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
at ClientRequest.emit (node:events:513:28)
at TLSSocket.socketErrorListener (node:_http_client:494:9)
at TLSSocket.emit (node:events:513:28)
at emitErrorNT (node:internal/streams/destroy:157:8)
at emitErrorCloseNT (node:internal/streams/destroy:122:3)
at processTicksAndRejections (node:internal/process/task_queues:83:21)
2023-03-24 17:15:55.292 - error: roborock.0 (24384) Exception-Code: ENOTFOUND: getaddrinfo ENOTFOUND euiot.roborock.com
2023-03-24 17:15:55.299 - info: roborock.0 (24384) terminating
2023-03-24 17:15:55.301 - warn: roborock.0 (24384) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-03-24 17:15:55.944 - error: host.raspberrypi instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-03-24 17:15:55.945 - info: host.raspberrypi Restart adapter system.adapter.roborock.0 because enabled
2023-03-24 17:15:55.945 - warn: host.raspberrypi Do not restart adapter system.adapter.roborock.0 because restart loop detected

**Comment by copystring** [comment]
Ich denke, dass es in der dev branch behoben ist. Magst du das mal testen?
https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by DonToben** [comment]
@copystring 
Mit der aktuellen Dev besteht wieder das Problem, dass bei fehlender Internetverbindung iobroker den Roborock Adapter anhält, da zuviele Neustarts erkannt wurden.

**Comment by copystring** [comment]
Ich wusste gar nicht, dass es überhaupt gelöst ist, da ich von dir keine Rückmeldung bekommen habe. Jetzt wissen wir gar nicht ob es jemand behoben war. Wenn es behoben war, wüsste ich gar nicht warum es jetzt wieder auftaucht, da ich an der Logik nichts verändert habe.

**Comment by DonToben** [comment]
Oh. Ich dachte es war behoben, da das Ticket geschlossen wurde.
Ich habe es erst gestern wieder bemerkt, da nach langer Zeit wieder ein Fritzbox Update gemacht wurde. Da ist ja dann paar Minuten die Internetverbindung weg.

----------------------------------------

*Von: *copystring ***@***.***>
*An: *copystring/ioBroker.roborock ***@***.***>
*Kopie: *DonToben ***@***.***>; Author ***@***.***>
*Datum: *22.04.2023 08:39:29
*Betreff: *Re: [copystring/ioBroker.roborock] Roborock Adapter startet bei fehlender Internetverbindung immer wieder neu (Issue #118)

**Comment by copystring** [comment]
Tickets werden nach 14 Tagen automatisch geschlossen, wenn es keine weiteren Aktivitäten gab.

**Comment by copystring** [comment]
Wie reproduzierst du das? Wenn ich meine Verbindung zum Internet trenne, tritt das Problem nicht auf. Zumindest nicht nach 2 Minuten ohne Internet. Taucht das Problem sofort auf, oder erst später?

Ich habe nochmal einen Versuch zur aktuellen dev Version eingefügt. Bitte die neue dev mal testen und unbedingt Rückmeldung geben, ob es behoben ist.

https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by DonToben** [comment]
Hi, mit der aktuellen Dev ist es nicht behoben.
Habe für circa 10 Minuten das Netzwerkkabel aus dem Pi genommen. Danach wird nur der Roborock Adapter beendet.

[Roborock Log.txt](https://github.com/copystring/ioBroker.roborock/files/11303171/Roborock.Log.txt)

**Comment by copystring** [comment]
OK. Danke für die Rückmeldung. Ich konnte den Fehler jetzt reproduzieren und beheben. Bitte nochmal mit der neuen dev testen.

**Comment by DonToben** [comment]
Scheint jetzt gelöst zu sein. Danke.

**Comment by copystring** [comment]
👍
Fixed via https://github.com/copystring/ioBroker.roborock/commit/1e4e240a2d8d12b353fcfa0a8bd692ec3f67ad63
