### ISSUE TITLE
Absturz bei fehlender Internetverbindung

### ISSUE THREAD

**Issue by ScumbagSteve** [copystring/ioBroker.roborock#147]
Wenn meine Internetverbindung mal weg ist, kommt der Adapter in eine Restart Loop:

```
2023-05-02 10:51:49.866 - error: roborock.0 (1440) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-05-02 10:51:49.866 - error: roborock.0 (1440) unhandled promise rejection: getaddrinfo EAI_AGAIN api-eu.roborock.com
2023-05-02 10:51:49.933 - error: roborock.0 (1440) Error: getaddrinfo EAI_AGAIN api-eu.roborock.com
at Function.AxiosError.from (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/lib/core/AxiosError.js:89:14)
at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/lib/adapters/http.js:577:25)
at RedirectableRequest.emit (node:events:513:28)
at RedirectableRequest.emit (node:domain:489:12)
at ClientRequest.eventHandlers. (/opt/iobroker/node_modules/follow-redirects/index.js:14:24)
at ClientRequest.emit (node:events:525:35)
at ClientRequest.emit (node:domain:489:12)
at TLSSocket.socketErrorListener (node:_http_client:494:9)
at TLSSocket.emit (node:events:513:28)
at TLSSocket.emit (node:domain:489:12)
2023-05-02 10:51:49.934 - error: roborock.0 (1440) Exception-Code: EAI_AGAIN: getaddrinfo EAI_AGAIN api-eu.roborock.com
2023-05-02 10:51:49.940 - info: roborock.0 (1440) terminating
2023-05-02 10:51:49.940 - warn: roborock.0 (1440) Terminated (UNCAUGHT_EXCEPTION): Without reason
```

Es wäre ideal wenn der Adapter bei fehlender Internetverbindung 5 Minuten wartet, und dann erneut versucht die Server zu kontaktieren. So ist es mir schon öfters passiert, dass ioBroker eine Restart loop erkannt hat, und den Adapter abschaltet.

**Comment by reihd** [comment]
irgendwie bin in zu dumm die Dev Version zu installieren, es bleibt immer bei 0.1.6. Wie kann ich die dev installieren?

**Comment by copystring** [comment]
Die dev kannst du hierüber installieren: https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by reihd** [comment]
Danke für die Antwort, aber bei mir bleibt es bei Version 0.1.6, warum auch immer, vielleicht gibt es ja bald eine neue Beta, solange kann man ja auch warten

**Comment by copystring** [comment]
Da steht immer 0.1.6 weil das kein neuer Release ist. Nur bei der dev steht #dev dahinter. Also 0.1.6#dev

**Comment by reihd** [comment]
Ok, danke, man lernt nie aus, habe es getestet, Adapter stürzt bei fehlender Internetverbindung nicht mehr ab, super Arbeit von dir
