### ISSUE TITLE
Adapter crash with two S7 MaxV devices

### ISSUE THREAD

**Issue by kopierschnitte** [copystring/ioBroker.roborock#21]
**Describe the bug**  
Adapter doesn't start with S7 MaxV robots

**Screenshots & Logfiles**  
ioBroker log:
`host.iobroker
2023-01-29 08:19:19.861	error	instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

roborock.0
2023-01-29 08:19:19.448	warn	State "roborock.0.Devices.3d0nqqH2ONtxeYVtkE3H4d.consumables.cleaning_brush_work_times" has no existing object, this might lead to an error in future versions

roborock.0
2023-01-29 08:19:19.448	warn	State "roborock.0.Devices.3d0nqqH2ONtxeYVtkE3H4d.consumables.strainer_work_times" has no existing object, this might lead to an error in future versions

roborock.0
2023-01-29 08:19:19.420	debug	dps debug: {"id":28,"result":[{"begin":1673098529,"end":1673100615,"duration":1955,"area":14240000,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":67,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.418	debug	dps debug: {"id":26,"result":[{"begin":1673443346,"end":1673445453,"duration":1823,"area":12277500,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":82,"wash_count":1,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.417	debug	dps debug: {"id":18,"result":[{"begin":1674377442,"end":1674378273,"duration":701,"area":6650000,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":27,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.415	debug	dps debug: {"id":30,"result":[{"begin":1672816905,"end":1672819367,"duration":2105,"area":30145000,"error":0,"complete":1,"start_type":2,"clean_type":1,"finish_reason":52,"dust_collection_status":1,"avoid_count":73,"wash_count":3,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.411	debug	dps debug: {"id":27,"result":[{"begin":1673441693,"end":1673442596,"duration":770,"area":6805000,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":24,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.408	debug	dps debug: {"id":29,"result":[{"begin":1673087904,"end":1673088810,"duration":778,"area":6795000,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":32,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.404	debug	dps debug: {"id":21,"result":[{"begin":1673794518,"end":1673796598,"duration":2080,"area":14382500,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":91,"wash_count":1,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.365	debug	dps debug: {"id":11,"result":[{"begin":1674766662,"end":1674768345,"duration":1563,"area":14082500,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":34,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.364	debug	dps debug: {"id":24,"result":[{"begin":1673725522,"end":1673727792,"duration":2150,"area":14295000,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":62,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.363	debug	dps debug: {"id":19,"result":[{"begin":1674292081,"end":1674294350,"duration":2154,"area":14755000,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":60,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.359	debug	dps debug: {"id":20,"result":[{"begin":1673806389,"end":1673807002,"duration":479,"area":4270000,"error":0,"complete":1,"start_type":2,"clean_type":2,"finish_reason":54,"dust_collection_status":1,"avoid_count":3,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.358	debug	dps debug: {"id":22,"result":[{"begin":1673792905,"end":1673793280,"duration":375,"area":3085000,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":12,"wash_count":1,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.357	debug	dps debug: {"id":15,"result":[{"begin":1674522197,"end":1674524890,"duration":2341,"area":14192500,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":0,"avoid_count":82,"wash_count":3,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.355	debug	dps debug: {"id":12,"result":[{"begin":1674546444,"end":1674548420,"duration":1632,"area":14375000,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":53,"wash_count":3,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.354	debug	dps debug: {"id":23,"result":[{"begin":1673790868,"end":1673791759,"duration":757,"area":6572500,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":25,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.352	debug	dps debug: {"id":13,"result":[{"begin":1674546431,"end":1674546433,"duration":2,"area":0,"error":0,"complete":0,"start_type":2,"clean_type":1,"finish_reason":37,"dust_collection_status":0,"avoid_count":0,"wash_count":0,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.350	debug	dps debug: {"id":25,"result":[{"begin":1673709970,"end":1673711137,"duration":1036,"area":8980000,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":15,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.347	debug	dps debug: {"id":14,"result":[{"begin":1674542249,"end":1674542741,"duration":366,"area":6537500,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":0,"avoid_count":13,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.345	debug	dps debug: {"id":17,"result":[{"begin":1674381086,"end":1674383413,"duration":2199,"area":14752500,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":70,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.342	debug	dps debug: {"id":16,"result":[{"begin":1674408702,"end":1674409650,"duration":813,"area":14437500,"error":0,"complete":1,"start_type":2,"clean_type":3,"finish_reason":56,"dust_collection_status":1,"avoid_count":21,"wash_count":2,"map_flag":0}]}

roborock.0
2023-01-29 08:19:19.339	debug	dps debug: {"id":9,"result":[{"max_multi_map":1,"max_bak_map":1,"multi_map_count":1,"map_info":[{"mapFlag":0,"add_time":1674768662,"length":13,"name":"Obergeschoss ","bak_maps":[{"mapFlag":4,"add_time":1671647485}]}]}]}

roborock.0
2023-01-29 08:19:19.337	debug	get_room_mapping: [[16,"8113307",1],[17,"8043479",15],[18,"8113298",1],[19,"8070271",8],[20,"8168423",8]]

roborock.0
2023-01-29 08:19:19.337	debug	dps debug: {"id":10,"result":[[16,"8113307",1],[17,"8043479",15],[18,"8113298",1],[19,"8070271",8],[20,"8168423",8]]}

roborock.0
2023-01-29 08:19:19.335	debug	dps debug: {"id":8,"result":[111,112,113,114,115,116,117,118,119,120,121,122,123,124,125]}

roborock.0
2023-01-29 08:19:19.332	debug	dps debug: {"id":3,"result":[{"main_brush_work_time":233648,"side_brush_work_time":233648,"filter_work_time":233648,"filter_element_work_time":0,"sensor_dirty_time":14330,"strainer_work_times":53,"dust_collection_work_times":179,"cleaning_brush_work_times":53}]}

roborock.0
2023-01-29 08:19:19.328	debug	dps debug: {"id":4,"result":{"ssid":"bwnetz","ip":"192.168.37.142","mac":"b0:4a:39:4b:a5:11","bssid":"b4:fb:e4:d5:64:a3","rssi":-66}}

roborock.0
2023-01-29 08:19:19.272	error	Cannot read properties of undefined (reading 'divider')

roborock.0
2023-01-29 08:19:19.272	error	TypeError: Cannot read properties of undefined (reading 'divider') at /opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:167:52 at processTicksAndRejections (node:internal/process/task_queues:96:5)

roborock.0
2023-01-29 08:19:19.271	error	unhandled promise rejection: Cannot read properties of undefined (reading 'divider')

roborock.0
2023-01-29 08:19:19.270	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

roborock.0
2023-01-29 08:19:19.268	debug	get_status: {"msg_ver":2,"msg_seq":10,"state":8,"battery":100,"clean_time":1563,"clean_area":14082500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"back_type":-1,"wash_phase":0,"wash_ready":0,"fan_power":104,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":203,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":3493,"is_exploring":0,"home_sec_status":0,"home_sec_enable_password":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":3,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":34,"mop_mode":300,"debug_mode":0,"collision_avoid_status":0,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0}

roborock.0
2023-01-29 08:19:19.267	debug	dps debug: {"id":1,"result":[{"msg_ver":2,"msg_seq":10,"state":8,"battery":100,"clean_time":1563,"clean_area":14082500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":1,"water_box_status":1,"back_type":-1,"wash_phase":0,"wash_ready":0,"fan_power":104,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":203,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":3493,"is_exploring":0,"home_sec_status":0,"home_sec_enable_password":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":3,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":34,"mop_mode":300,"debug_mode":0,"collision_avoid_status":0,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0}]}

roborock.0
2023-01-29 08:19:19.265	debug	dps debug: {"id":6,"result":[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}]}

roborock.0
2023-01-29 08:19:19.248	debug	dps debug: {"id":2,"result":{"water_box_mode":203}}

roborock.0
2023-01-29 08:19:19.244	debug	dps debug: {"id":7,"result":[{"carpet_clean_mode":1}]}

roborock.0
2023-01-29 08:19:19.227	debug	dps debug: {"id":5,"result":{"clean_time":233648,"clean_area":2087355000,"clean_count":221,"dust_collection_count":179,"records":[1674766662,1674546444,1674546431,1674542249,1674522197,1674408702,1674381086,1674377442,1674292081,1673806389,1673794518,1673792905,1673790868,1673725522,1673709970,1673443346,1673441693,1673098529,1673087904,1672816905]}}

roborock.0
2023-01-29 08:19:19.157	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

roborock.0
2023-01-29 08:19:19.156	info	terminating

roborock.0
2023-01-29 08:19:19.153	error	Cannot read properties of undefined (reading 'model')

roborock.0
2023-01-29 08:19:19.152	error	TypeError: Cannot read properties of undefined (reading 'model') at Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:170:39)

roborock.0
2023-01-29 08:19:19.151	error	unhandled promise rejection: Cannot read properties of undefined (reading 'model')

roborock.0
2023-01-29 08:19:19.151	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

roborock.0
2023-01-29 08:19:19.145	debug	get_room_mapping

roborock.0
2023-01-29 08:19:19.144	debug	getParameter: get_room_mapping

roborock.0
2023-01-29 08:19:19.143	debug	getParameter: get_multi_maps_list

roborock.0
2023-01-29 08:19:19.142	debug	Firmware features request

roborock.0
2023-01-29 08:19:19.141	debug	getParameter: get_fw_features

roborock.0
2023-01-29 08:19:19.140	debug	getParameter: get_carpet_clean_mode

roborock.0
2023-01-29 08:19:19.138	debug	getParameter: get_carpet_mode

roborock.0
2023-01-29 08:19:19.135	debug	getParameter: get_network_info

roborock.0
2023-01-29 08:19:19.134	debug	getParameter: get_consumable

roborock.0
2023-01-29 08:19:19.132	debug	getParameter: get_water_box_custom_mode

roborock.0
2023-01-29 08:19:19.126	debug	getParameter: get_status

roborock.0
2023-01-29 08:19:19.124	debug	Latest data requested

roborock.0
2023-01-29 08:19:18.782	debug	Robot key: roborock.vacuum.a27

roborock.0
2023-01-29 08:19:18.780	info	MQTT initialized

roborock.0
2023-01-29 08:19:18.724	debug	RoomIDs debug: {"8043477":"Wohnzimmer","8043479":"Badezimmer","8070271":"Flur","8113298":"Schlafzimmer","8113307":"Laura","8168423":"Schrank","10294341":"Treppenhaus"}

roborock.0
2023-01-29 08:19:18.431	info	starting. Version 0.0.2-alpha.0 (non-npm: copystring/ioBroker.roborock#5068a227e23bb1602d0411a9a6df66025b27cbd4) in /opt/iobroker/node_modules/iobroker.roborock, node: v16.19.0, js-controller: 4.0.24

roborock.0
2023-01-29 08:19:18.121	debug	States connected to redis: 127.0.0.1:6379

roborock.0
2023-01-29 08:19:18.113	debug	States create User PubSub Client

roborock.0
2023-01-29 08:19:18.111	debug	States create System PubSub Client

roborock.0
2023-01-29 08:19:18.103	debug	Redis States: Use Redis connection: 127.0.0.1:6379

roborock.0
2023-01-29 08:19:18.074	debug	Objects connected to redis: 127.0.0.1:6379

roborock.0
2023-01-29 08:19:18.068	debug	Objects client initialize lua scripts

roborock.0
2023-01-29 08:19:17.657	debug	Objects create User PubSub Client

roborock.0
2023-01-29 08:19:17.656	debug	Objects create System PubSub Client

roborock.0
2023-01-29 08:19:17.654	debug	Objects client ready ... initialize now`

**Versions:**  
 - Adapter version: 0.0.2-alpha.0
 - JS-Controller version: 4.0.24
 - Node version: 16.19.0
 - Operating system: Ubuntu x86

**Additional context**  
Maybe it's a problem that I use two (identical) robots in my home?
Both are devices of type roborock.vacuum.a27

**Comment by copystring** [comment]
Post your roborock.0.HomeData here please.

**Comment by kopierschnitte** [comment]
Of course, sorry. I hope there's no sensible data inside ;-)
`
{
	"id": 3251318,
	"name": "My Home",
	"lon": null,
	"lat": null,
	"geoName": null,
	"products": [
		{
			"id": "42yfoQm5eOY3gARZw6xgU",
			"name": "Roborock S7 MaxV",
			"code": "a27",
			"model": "roborock.vacuum.a27",
			"iconUrl": null,
			"attribute": null,
			"capability": 0,
			"category": "robot.vacuum.cleaner",
			"schema": [
				{
					"id": "101",
					"name": "rpc_request",
					"code": "rpc_request",
					"mode": "rw",
					"type": "RAW",
					"property": null,
					"desc": null
				},
				{
					"id": "102",
					"name": "rpc_response",
					"code": "rpc_response",
					"mode": "rw",
					"type": "RAW",
					"property": null,
					"desc": null
				},
				{
					"id": "120",
					"name": "错误代码",
					"code": "error_code",
					"mode": "ro",
					"type": "ENUM",
					"property": "{\"range\": []}",
					"desc": null
				},
				{
					"id": "121",
					"name": "设备状态",
					"code": "state",
					"mode": "ro",
					"type": "ENUM",
					"property": "{\"range\": []}",
					"desc": null
				},
				{
					"id": "122",
					"name": "设备电量",
					"code": "battery",
					"mode": "ro",
					"type": "ENUM",
					"property": "{\"range\": []}",
					"desc": null
				},
				{
					"id": "123",
					"name": "清扫模式",
					"code": "fan_power",
					"mode": "rw",
					"type": "ENUM",
					"property": "{\"range\": []}",
					"desc": null
				},
				{
					"id": "124",
					"name": "拖地模式",
					"code": "water_box_mode",
					"mode": "rw",
					"type": "ENUM",
					"property": "{\"range\": []}",
					"desc": null
				},
				{
					"id": "125",
					"name": "主刷寿命",
					"code": "main_brush_life",
					"mode": "rw",
					"type": "VALUE",
					"property": "{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}",
					"desc": null
				},
				{
					"id": "126",
					"name": "边刷寿命",
					"code": "side_brush_life",
					"mode": "rw",
					"type": "VALUE",
					"property": "{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}",
					"desc": null
				},
				{
					"id": "127",
					"name": "滤网寿命",
					"code": "filter_life",
					"mode": "rw",
					"type": "VALUE",
					"property": "{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}",
					"desc": null
				},
				{
					"id": "128",
					"name": "额外状态",
					"code": "additional_props",
					"mode": "ro",
					"type": "RAW",
					"property": null,
					"desc": null
				},
				{
					"id": "130",
					"name": "完成事件",
					"code": "task_complete",
					"mode": "ro",
					"type": "RAW",
					"property": null,
					"desc": null
				},
				{
					"id": "131",
					"name": "电量不足任务取消",
					"code": "task_cancel_low_power",
					"mode": "ro",
					"type": "RAW",
					"property": null,
					"desc": null
				},
				{
					"id": "132",
					"name": "运动中任务取消",
					"code": "task_cancel_in_motion",
					"mode": "ro",
					"type": "RAW",
					"property": null,
					"desc": null
				},
				{
					"id": "133",
					"name": "充电状态",
					"code": "charge_status",
					"mode": "ro",
					"type": "RAW",
					"property": null,
					"desc": null
				},
				{
					"id": "134",
					"name": "烘干状态",
					"code": "drying_status",
					"mode": "ro",
					"type": "RAW",
					"property": null,
					"desc": null
				}
			]
		}
	],
	"devices": [
		{
			"duid": "3d0nqqH2ONtxeYVtkE3H4d",
			"name": "Robo Obergeschoss",
			"attribute": null,
			"activeTime": 1662555158,
			"localKey": "3fkHSNp2IFyXkRTm",
			"runtimeEnv": null,
			"timeZoneId": "Europe/Berlin",
			"iconUrl": "",
			"productId": "42yfoQm5eOY3gARZw6xgU",
			"lon": null,
			"lat": null,
			"share": false,
			"shareTime": null,
			"online": true,
			"fv": "02.56.02",
			"pv": "1.0",
			"roomId": 8113298,
			"tuyaUuid": null,
			"tuyaMigrated": false,
			"extra": "{\"RRPhotoPrivacyVersion\": \"1\", \"RRMonitorPrivacyVersion\": \"1\"}",
			"sn": "R21ETS21602300",
			"featureSet": "2234201184108543",
			"newFeatureSet": "0000000000002041",
			"deviceStatus": {
				"120": 0,
				"121": 8,
				"122": 100,
				"123": 104,
				"124": 203,
				"125": 79,
				"126": 68,
				"127": 57,
				"128": 0,
				"133": 1
			},
			"silentOtaSwitch": true
		},
		{
			"duid": "7mbLmMxObHezlLdZxUkMxJ",
			"name": "Robo Erdgeschoss",
			"attribute": null,
			"activeTime": 1662107542,
			"localKey": "UlYZdIcl0zRnfMWS",
			"runtimeEnv": null,
			"timeZoneId": "Europe/Berlin",
			"iconUrl": "",
			"productId": "42yfoQm5eOY3gARZw6xgU",
			"lon": null,
			"lat": null,
			"share": false,
			"shareTime": null,
			"online": true,
			"fv": "02.56.02",
			"pv": "1.0",
			"roomId": 10294341,
			"tuyaUuid": null,
			"tuyaMigrated": false,
			"extra": "{\"RRPhotoPrivacyVersion\": \"1\", \"RRMonitorPrivacyVersion\": \"1\"}",
			"sn": "R21ETS22803070",
			"featureSet": "2234201184108543",
			"newFeatureSet": "0000000000002041",
			"deviceStatus": {
				"120": 0,
				"121": 8,
				"122": 100,
				"123": 104,
				"124": 203,
				"125": 70,
				"126": 54,
				"127": 39,
				"128": 0,
				"133": 1
			},
			"silentOtaSwitch": true
		}
	],
	"receivedDevices": [],
	"rooms": [
		{
			"id": 10294341,
			"name": "Treppenhaus"
		},
		{
			"id": 8168423,
			"name": "Schrank"
		},
		{
			"id": 8113307,
			"name": "Laura"
		},
		{
			"id": 8113298,
			"name": "Schlafzimmer"
		},
		{
			"id": 8070271,
			"name": "Flur"
		},
		{
			"id": 8043479,
			"name": "Badezimmer"
		},
		{
			"id": 8043477,
			"name": "Wohnzimmer"
		}
	]
}
`

**Comment by copystring** [comment]
Thank you. I found the issue. There is indeed a problem with multiple robots. Especially when both are the same robot.

**Comment by copystring** [comment]
Try this update: https://github.com/copystring/ioBroker.roborock/tree/report_unknown_attributes

**Comment by kopierschnitte** [comment]
Perfect, seems to work now. I've got the following unknown attributes to report:
`
roborock.0 | 2023-01-29 15:17:49.055 | error | Unsported attribute: charge_status of get_status. Please contact the dev to add the newly found attribute of your robot.
-- | -- | -- | --
roborock.0 | 2023-01-29 15:17:49.055 | error | Unsported attribute: switch_map_mode of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-29 15:17:49.055 | error | Unsported attribute: collision_avoid_status of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-29 15:17:49.054 | error | Unsported attribute: avoid_count of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-29 15:17:49.054 | error | Unsported attribute: home_sec_enable_password of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-29 15:17:49.054 | error | Unsported attribute: home_sec_status of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-29 15:17:49.054 | error | Unsported attribute: is_exploring of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-29 15:17:49.054 | error | Unsported attribute: camera_status of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-29 15:17:49.054 | error | Unsported attribute: wash_ready of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-29 15:17:49.053 | error | Unsported attribute: wash_phase of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-29 15:17:49.053 | error | Unsported attribute: back_type of get_status. Please contact the dev to add the newly found attribute of your robot.`

... but since this is a different issue, I'll happily close this one.
