### ISSUE TITLE
Programme ausführen

### ISSUE THREAD

**Issue by krobipd** [copystring/ioBroker.roborock#351]
Hallo und erstmal vielen Dank deine harte Arbeit und diesen Adapter.

Ich habe seit kurzem einen Roborock s8+ und verwende daher deinen Adapter. Jetzt fehlt mir aber irgendwie die Möglichkeit die in der App erstellten Programme außerhalb der App aufzurufen.

Ich finde weder eine Möglichkeit via Alexa Skill dies zu machen noch in deinem Adapter.
Daher mein Feature Request - per App gespeicherte Programme über den Adapter auflisten und ausführbar machen.

Wäre richtig Klasse.

**Comment by copystring** [comment]
Hi,
ja sehr gerne aber da ich keinen S8 habe brauche ich dabei Hilfe.
Du müsstest also den Datenverkehr mitschneiden.
Wie das geht, steht hier: https://github.com/copystring/ioBroker.roborock/wiki/Sniffing-Roborock-MQTT-traffic

Dann das entsprechende Debug Log hier anhängen.

Ja, ist ziemlich kompliziert geht aber nicht anders.

**Comment by krobipd** [comment]
Serwus

entschuldige die späte Antwort, danke für die Info - steht auf alle Fälle auf meiner to-do Liste.

was mich aber etwas wundert, diese Funktion haben ja - fast - alle Roborock saugroboter und ich keine s8 exklusive Funktion. Warum ist es dann wichtig ob ich einen s8 habe? 

wäre echt toll wenn man diese Programme starten könnte.

**Comment by copystring** [comment]
Hi,
kein Problem. Alles gut.

Verschiedene Generationen von Saugrobotern haben verschiedene Befehle. Ich meine, dass die neueren Roboter die Zeitpläne auf den Server von Roborock speichern. Der Befehl und die entsprechenden Parameter dafür sind mir nicht bekannt.
Deshalb müsste man den Datenverkehr mitschneiden. Erst danach kann ich das implantieren.

Wenn dir das Sniffing nicht liegt, kannst du den Saugroboter mit mir über die App teilen und ich kann das für dich machen. Du müsstest mir dann nur sagen, wo du das genau einstellst.

**Comment by krobipd** [comment]
https://github.com/copystring/ioBroker.roborock/assets/27220902/c3ac06e7-3763-441b-9327-18e403aafca8

serwus, hier ein video. ich rufe einfach die roborock app auf - da ich nur einen Roboter habe - wird dieser sofort angezeigt und dann habe ich unten "Programme" und darunter meine gespeicherten Programme, dort einfach auf play drücken und das Programm wird ausgeführt.

wie du im clip siehst kann man sonst auch die Programme editieren/erstellen, für mich wäre an sich nur das starten der Programme interessant. ich gebe dir dann gleich mal den Roboter frei ;-)

**Comment by copystring** [comment]
OK. Um das zu testen, müsste ich mal so ein Programm starten und den Datenverkehr mitschneiden. Wann wäre das OK für dich?

**Comment by krobipd** [comment]
supi, gute frage - im laufe des vormittags so zwischen 9 und 12 wäre super. du könntest das "täglich" Programm gerne starten, nutzen wir sonst e jeden tag :-P

**Comment by copystring** [comment]
Da bin ich an der Arbeit. Wie sieht es am Wochenende aus? Gleiche Uhrzeit?

**Comment by krobipd** [comment]
oh 🙈 hätte mir auch klar sein können :-P sonst auch gerne mal am Abend 18-22 Uhr?

**Comment by copystring** [comment]
Gern. Habe schon mal was angefangen.
Kann das dann vielleicht morgen oder am Wochenende mal testen.

![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/908c4655-58f6-4a4f-b820-99739175532f)

**Comment by copystring** [comment]
Teste bitte mal die neue dev. Dort kannst du unter dem Ordner `programs` die aktuellen Programme im Detail finden.
Zum Starten eines Programms im Ordner `programs` den entsprechenden Plan auswählen.
Wichtig ist, dass du den Haken bei `Bestätigt` setzt. Dann sollte das entsprechende Programm ausgeführt werden.

![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/54e2eb33-98cb-4711-bd04-d83d2d70ec98)

**Comment by krobipd** [comment]
Super Mega cool 😎 🥳
Mach ich 👍 hab dir auch auf Discord geschrieben vl ein kürzerer weg wenn du was brauchst oder so

**Comment by krobipd** [comment]
hab ich gemacht ;-)
gerade ausprobiert aber leider macht der Roboter absolut nix :-(

**Comment by krobipd** [comment]
mega 🥳 ja hab ich bemerkt :-) tausend dank, werd ich morgen dann mal selbst testen.

**Comment by krobipd** [comment]
so jetzt hab Ichs doch gleich getestet, funktioniert jetzt wie beschrieben 🥳

aber 
habe ein neues program in der app angelegt (kannst du jederzeit nutzen heißt Testing) und dies wurde nicht automatisch eingetragen, nach einem Neustart des Adapters war es dann aber da 😊

jetzt habe ich das ganze versucht via blockly zu steuern und naja des hat den adapter ganz schön aufgestellt. hab schon so einige blockies gemacht aber musste noch nie auf "bestätigt" Rücksicht nehmen. hab also gemerkt mit aktualisieren gehts.

hab dann diesen block (natürlich war er da aktiviert) einfach mal gestartet und der adapter hat das mit haufenweiße Fehlermeldungen quittiert

<img width="559" alt="Bildschirmfoto 2023-12-06 um 22 20 45" src="https://github.com/copystring/ioBroker.roborock/assets/27220902/4b254591-9fcd-4412-96c6-63ee2f4ff571">



2023-12-06 22:16:58.623 - error: roborock.0 (72389) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-12-06 22:16:58.624 - error: roborock.0 (72389) unhandled promise rejection: Request failed with status code 400
2023-12-06 22:16:58.704 - error: roborock.0 (72389) AxiosError: Request failed with status code 400
at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:19:12)
at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:585:11)
at IncomingMessage.emit (node:events:526:35)
at IncomingMessage.emit (node:domain:488:12)
at endReadableNT (node:internal/streams/readable:1589:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-12-06 22:16:58.704 - error: roborock.0 (72389) Exception-Code: ERR_BAD_REQUEST: Request failed with status code 400
2023-12-06 22:16:58.717 - warn: roborock.0 (72389) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-06 22:16:59.229 - error: roborock.0 (72389) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-06 22:16:59.230 - error: roborock.0 (72389) unhandled promise rejection: Connection is closed.
2023-12-06 22:16:59.231 - error: roborock.0 (72389) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:629:26)
at Socket.emit (node:events:514:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2023-12-06 22:16:59.231 - error: roborock.0 (72389) Connection is closed.
2023-12-06 22:16:59.234 - error: roborock.0 (72389) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-06 22:16:59.234 - error: roborock.0 (72389) unhandled promise rejection: Connection is closed.
2023-12-06 22:16:59.235 - error: roborock.0 (72389) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:629:26)
at Socket.emit (node:events:514:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2023-12-06 22:16:59.236 - error: roborock.0 (72389) Connection is closed.
2023-12-06 22:16:59.237 - error: roborock.0 (72389) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-06 22:16:59.237 - error: roborock.0 (72389) unhandled promise rejection: Connection is closed.
2023-12-06 22:16:59.238 - error: roborock.0 (72389) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:629:26)
at Socket.emit (node:events:514:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2023-12-06 22:16:59.238 - error: roborock.0 (72389) Connection is closed.
2023-12-06 22:16:59.239 - error: roborock.0 (72389) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-06 22:16:59.239 - error: roborock.0 (72389) unhandled promise rejection: Connection is closed.
2023-12-06 22:16:59.239 - error: roborock.0 (72389) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:629:26)
at Socket.emit (node:events:514:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2023-12-06 22:16:59.239 - error: roborock.0 (72389) Connection is closed.
2023-12-06 22:16:59.241 - error: roborock.0 (72389) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-06 22:16:59.241 - error: roborock.0 (72389) unhandled promise rejection: Connection is closed.
2023-12-06 22:16:59.242 - error: roborock.0 (72389) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:629:26)
at Socket.emit (node:events:514:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2023-12-06 22:16:59.242 - error: roborock.0 (72389) Connection is closed.
2023-12-06 22:16:59.302 - error: host.krobis-iotctr Caught by controller[0]: Downloading AlexxIT/go2rtc@v1.8.4...
2023-12-06 22:16:59.303 - error: host.krobis-iotctr Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-06 22:16:59.303 - error: host.krobis-iotctr Caught by controller[2]: AxiosError: Request failed with status code 400
2023-12-06 22:16:59.303 - error: host.krobis-iotctr Caught by controller[2]: at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:19:12)
2023-12-06 22:16:59.303 - error: host.krobis-iotctr Caught by controller[2]: at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:585:11)
2023-12-06 22:16:59.303 - error: host.krobis-iotctr Caught by controller[2]: at IncomingMessage.emit (node:events:526:35)
2023-12-06 22:16:59.303 - error: host.krobis-iotctr Caught by controller[2]: at IncomingMessage.emit (node:domain:488:12)
2023-12-06 22:16:59.303 - error: host.krobis-iotctr Caught by controller[2]: at endReadableNT (node:internal/streams/readable:1589:12)
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[2]: at processTicksAndRejections (node:internal/process/task_queues:82:21)
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[3]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[4]: Error: Connection is closed.
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[4]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[4]: at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[4]: at Object.onceWrapper (node:events:629:26)
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[4]: at Socket.emit (node:events:514:28)
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[4]: at Socket.emit (node:domain:488:12)
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[4]: at TCP. (node:net:337:12)
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[5]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[6]: Error: Connection is closed.
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[6]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
2023-12-06 22:16:59.304 - error: host.krobis-iotctr Caught by controller[6]: at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[6]: at Object.onceWrapper (node:events:629:26)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[6]: at Socket.emit (node:events:514:28)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[6]: at Socket.emit (node:domain:488:12)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[6]: at TCP. (node:net:337:12)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[7]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[8]: Error: Connection is closed.
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[8]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[8]: at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[8]: at Object.onceWrapper (node:events:629:26)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[8]: at Socket.emit (node:events:514:28)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[8]: at Socket.emit (node:domain:488:12)
2023-12-06 22:16:59.305 - error: host.krobis-iotctr Caught by controller[8]: at TCP. (node:net:337:12)
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[9]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[10]: Error: Connection is closed.
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[10]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[10]: at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[10]: at Object.onceWrapper (node:events:629:26)
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[10]: at Socket.emit (node:events:514:28)
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[10]: at Socket.emit (node:domain:488:12)
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[10]: at TCP. (node:net:337:12)
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[11]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[12]: Error: Connection is closed.
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[12]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[12]: at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
2023-12-06 22:16:59.306 - error: host.krobis-iotctr Caught by controller[12]: at Object.onceWrapper (node:events:629:26)
2023-12-06 22:16:59.307 - error: host.krobis-iotctr Caught by controller[12]: at Socket.emit (node:events:514:28)
2023-12-06 22:16:59.307 - error: host.krobis-iotctr Caught by controller[12]: at Socket.emit (node:domain:488:12)
2023-12-06 22:16:59.307 - error: host.krobis-iotctr Caught by controller[12]: at TCP. (node:net:337:12)
2023-12-06 22:16:59.307 - error: host.krobis-iotctr instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by molkemolko** [comment]
Hi, ich würde auch gerne das Programme Feature nutzen, finde die entsprechenden Objekte allerdings nicht im iobroker. Ich habe 0.4.4 installiert. Oder muss ich noch eine andere dev Variante installieren? :)

**Comment by copystring** [comment]
Hi, was meinst du mit "eine andere dev"? Entweder hast du den Release (0.4.4) oder dev installiert.

**Comment by molkemolko** [comment]
Ah sorry, ich habe den 0.4.4 Release installiert. Wie installiere ich die dev Version? Wenn es zu komplex ist, warte ich einfach auf den neuen Release. 😊

**Comment by copystring** [comment]
Du kannst die dev über diesen Link https://github.com/copystring/ioBroker.roborock/tree/dev installieren

**Comment by krobipd** [comment]
> Ah sorry, ich habe den 0.4.4 Release installiert. Wie installiere ich die dev Version? Wenn es zu komplex ist, warte ich einfach auf den neuen Release. 😊

serwus

hier ein link wo erklärt wird wie man via url einen adapter installiert - nimm die untere Anleitung für admin 5.x (ist aktuell das selbe - optisch)

statt der angezeigten url nimmst du bitte die url die copystring gepostet hat.

https://github.com/ioBroker/ioBroker.zigbee/wiki/GIT-install

**Comment by molkemolko** [comment]
Ach perfekt, das ist dann ja doch einfacher als gedacht. :) 

URL Installation war mir bekannt, nur der dev Pfad nicht. 

Vielen lieben Dank euch beiden! :)

**Comment by krobipd** [comment]
Serwus

mir ist nochmals aufgefallen.
Beim entfernen von Programmen werden diese im Adapter nicht gelöscht, auch nicht nachdem restart des Adapters.

**Comment by krobipd** [comment]
hey ;-)

ich hab mal die aktuelle dev installiert, auch die Datenpunkte mal neu eingelesen.
jedenfalls funktioniert das mit den Programme nicht mehr :-(

**Comment by krobipd** [comment]
ah ok es funktioniert doch alles, aber nicht mehr mit "bestätigt" sondern jetzt ohne bestätigt. aber gut, es funktioniert ja doch ;-)
