### ISSUE TITLE
avoid_count Fehler

### ISSUE THREAD

**Issue by bernhaddl** [copystring/ioBroker.roborock#429]
Hallo,

ich habe bei meinem Roborock S8 folgende Fehlermeldungen
Adapter Version 0.4.4

<html>
<body>

roborock.0 | 2023-11-09 10:18:06.323 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.19.avoid_count" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
roborock.0 | 2023-11-09 10:18:06.293 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.18.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:06.221 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.17.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:06.149 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.16.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:06.024 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.15.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.954 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.14.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.877 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.13.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.763 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.12.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.737 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.11.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.669 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.10.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.552 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.9.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.483 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.8.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.455 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.7.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.342 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.6.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.271 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.5.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.245 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.4.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.177 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.3.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:05.101 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.2.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:04.980 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.1.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:04.949 | warn | State "roborock.0.Devices.xxxxxxxxxxxx.cleaningInfo.Records.0.avoid_count" has no existing object, this might lead to an error in future versions
roborock.0 | 2023-11-09 10:18:04.337 | warn | Failed to execute load_multi_map on robot xxxxxxxxxxxx Error: There was an error processing the request with id 5271 error: {"code":-10007,"message":"invalid status"}

</body>
</html>

**Comment by copystring** [comment]
Danke. Fixed in via https://github.com/copystring/ioBroker.roborock/commit/f804b9a2b0bab125d42af046e5ba9c244dc24718.
Du müsstest auf den nächsten Release warten oder die dev testen.

**Comment by bernhaddl** [comment]
Dieser Fehler ist mit der dev Version jetzt weg, allerdings hab ich minütlich einen neuen:


roborock.0
2023-11-16 07:37:57.544	error	Failed to execute load_multi_map on robot 6jWcsplHN1hqrmHaTNyLfB Error: There was an error processing the request with id 1510 error: {"code":-10003,"message":"action locked"} at EventEmitter.listener102 (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:286:14) at EventEmitter.emit (/opt/iobroker/node_modules/eventemitter2/lib/eventemitter2.js:1047:22) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:182:9) at MqttClient.emit (node:events:514:28) at handlePublish (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/publish.ts:172:11) at handle (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/index.ts:29:17) at work (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:728:17) at Writable.writable._write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:752:4) at writeOrBuffer (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) at _write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)


roborock.0
2023-11-16 07:36:57.631	error	Failed to execute load_multi_map on robot 6jWcsplHN1hqrmHaTNyLfB Error: There was an error processing the request with id 4752 error: {"code":-10003,"message":"action locked"} at EventEmitter.listener102 (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:286:14) at EventEmitter.emit (/opt/iobroker/node_modules/eventemitter2/lib/eventemitter2.js:1047:22) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:182:9) at MqttClient.emit (node:events:514:28) at handlePublish (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/publish.ts:172:11) at handle (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/index.ts:29:17) at work (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:728:17) at Writable.writable._write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:752:4) at writeOrBuffer (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) at _write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)


roborock.0
2023-11-16 07:35:57.689	error	Failed to execute load_multi_map on robot 6jWcsplHN1hqrmHaTNyLfB Error: There was an error processing the request with id 4076 error: {"code":-10003,"message":"action locked"} at EventEmitter.listener102 (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:286:14) at EventEmitter.emit (/opt/iobroker/node_modules/eventemitter2/lib/eventemitter2.js:1047:22) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:182:9) at MqttClient.emit (node:events:514:28) at handlePublish (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/publish.ts:172:11) at handle (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/index.ts:29:17) at work (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:728:17) at Writable.writable._write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:752:4) at writeOrBuffer (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) at _write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)


roborock.0
2023-11-16 07:34:57.703	error	Failed to execute load_multi_map on robot 6jWcsplHN1hqrmHaTNyLfB Error: There was an error processing the request with id 3388 error: {"code":-10003,"message":"action locked"} at EventEmitter.listener102 (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:286:14) at EventEmitter.emit (/opt/iobroker/node_modules/eventemitter2/lib/eventemitter2.js:1047:22) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:182:9) at MqttClient.emit (node:events:514:28) at handlePublish (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/publish.ts:172:11) at handle (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/index.ts:29:17) at work (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:728:17) at Writable.writable._write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:752:4) at writeOrBuffer (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:334:12) at _write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)

**Comment by copystring** [comment]
`action locked` bedeutet, dass dein Saugroboter irgendwie beschäftigt ist. starte den mal neu.
