### ISSUE TITLE
Support for Roborock Zeo One

### ISSUE THREAD

**Issue by ChrMaass** [copystring/ioBroker.roborock#432]
It would be great if you would support the new Roborock Zeo One washer-dryer. I don't have a robot vacuum cleaner, which is probably why I get some error messages after starting the instance. 

I would be happy to test it.

**Comment by copystring** [comment]
Sure. Post a debug log and I'll see what I can do

**Comment by ChrMaass** [comment]
Here it is:

`2023-11-13 22:58:06.821 - info: host.iobroker "system.adapter.roborock.0" enabled
--
2023-11-13 22:58:07.352 - info: host.iobroker instance system.adapter.roborock.0 started with pid 1612250
2023-11-13 22:58:08.610 - debug: roborock.0 (1612250) Redis Objects: Use Redis connection: 127.0.0.1:9001
2023-11-13 22:58:08.708 - debug: roborock.0 (1612250) Objects client ready ... initialize now
2023-11-13 22:58:08.710 - debug: roborock.0 (1612250) Objects create System PubSub Client
2023-11-13 22:58:08.710 - debug: roborock.0 (1612250) Objects create User PubSub Client
2023-11-13 22:58:08.980 - debug: roborock.0 (1612250) Objects client initialize lua scripts
2023-11-13 22:58:08.985 - debug: roborock.0 (1612250) Objects connected to redis: 127.0.0.1:9001
2023-11-13 22:58:09.107 - debug: roborock.0 (1612250) Redis States: Use Redis connection: 127.0.0.1:9000
2023-11-13 22:58:09.175 - debug: roborock.0 (1612250) States create System PubSub Client
2023-11-13 22:58:09.176 - debug: roborock.0 (1612250) States create User PubSub Client
2023-11-13 22:58:09.371 - debug: roborock.0 (1612250) States connected to redis: 127.0.0.1:9000
2023-11-13 22:58:09.476 - debug: roborock.0 (1612250) Plugin sentry Initialize Plugin (enabled=true)
2023-11-13 22:58:09.823 - info: roborock.0 (1612250) starting. Version 0.4.4 in /opt/iobroker/node_modules/iobroker.roborock, node: v18.17.1, js-controller: 5.0.16
2023-11-13 22:58:10.587 - info: roborock.0 (1612250) MQTT initialized
2023-11-13 22:58:10.588 - debug: roborock.0 (1612250) RoomIDs debug: {}
2023-11-13 22:58:10.589 - debug: roborock.0 (1612250) arch: x64
2023-11-13 22:58:10.589 - debug: roborock.0 (1612250) platform: linux
2023-11-13 22:58:10.589 - debug: roborock.0 (1612250) System type: go2rtc_linux_amd64
2023-11-13 22:58:10.590 - debug: roborock.0 (1612250) downloadURL: https://github.com/AlexxIT/go2rtc/releases/download/v1.3.0/go2rtc_linux_amd64
2023-11-13 22:58:11.306 - debug: roborock.0 (1612250) Made ./lib/go2rtc/go2rtc_linux_amd64 executable
2023-11-13 22:58:11.371 - debug: roborock.0 (1612250) homedata successfully updated
2023-11-13 22:58:12.245 - error: roborock.0 (1612250) uncaught exception: Unknown protocol version
2023-11-13 22:58:12.245 - error: roborock.0 (1612250) Error: Unknown protocol version
at roborock_mqtt_connector._decodeMsg (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:141:10)
at MqttClient. (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:166:22)
at MqttClient.emit (node:events:514:28)
at handlePublish (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/publish.ts:172:11)
at handle (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/index.ts:29:17)
at work (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:735:17)
at Writable.writable._write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:759:4)
at writeOrBuffer (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:334:12)
at _write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)
at Writable.write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)
2023-11-13 22:58:12.246 - error: roborock.0 (1612250) Unknown protocol version
2023-11-13 22:58:12.262 - info: roborock.0 (1612250) terminating
2023-11-13 22:58:12.263 - debug: roborock.0 (1612250) Plugin sentry destroyed
2023-11-13 22:58:12.263 - warn: roborock.0 (1612250) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-11-13 22:58:12.637 - error: host.iobroker Caught by controller[0]: Downloading AlexxIT/go2rtc@v1.8.2...
2023-11-13 22:58:12.638 - error: host.iobroker Caught by controller[1]: Error: Unknown protocol version
2023-11-13 22:58:12.638 - error: host.iobroker Caught by controller[1]: at roborock_mqtt_connector._decodeMsg (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:141:10)
2023-11-13 22:58:12.638 - error: host.iobroker Caught by controller[1]: at MqttClient. (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:166:22)
2023-11-13 22:58:12.638 - error: host.iobroker Caught by controller[1]: at MqttClient.emit (node:events:514:28)
2023-11-13 22:58:12.638 - error: host.iobroker Caught by controller[1]: at handlePublish (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/publish.ts:172:11)
2023-11-13 22:58:12.638 - error: host.iobroker Caught by controller[1]: at handle (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/handlers/index.ts:29:17)
2023-11-13 22:58:12.638 - error: host.iobroker Caught by controller[1]: at work (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:735:17)
2023-11-13 22:58:12.638 - error: host.iobroker Caught by controller[1]: at Writable.writable._write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/src/lib/client.ts:759:4)
2023-11-13 22:58:12.638 - error: host.iobroker Caught by controller[1]: at writeOrBuffer (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:334:12)
2023-11-13 22:58:12.639 - error: host.iobroker Caught by controller[1]: at _write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:283:10)
2023-11-13 22:58:12.639 - error: host.iobroker Caught by controller[1]: at Writable.write (/opt/iobroker/node_modules/iobroker.roborock/node_modules/readable-stream/lib/internal/streams/writable.js:286:10)
2023-11-13 22:58:12.639 - error: host.iobroker instance system.adapter.roborock.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2023-11-13 22:58:12.639 - info: host.iobroker Restart adapter system.adapter.roborock.0 because enabled

`

**Comment by copystring** [comment]
Thanks. Please install this branch https://github.com/copystring/ioBroker.roborock/tree/zeo_one and post a new log. Nothing fixed yet. I added extra logging to find out which protocol version is used.

**Comment by ChrMaass** [comment]
Here it is

`
2023-11-15 18:51:23.331 - info: host.iobroker "system.adapter.roborock.0" enabled
2023-11-15 18:51:23.875 - info: host.iobroker instance system.adapter.roborock.0 started with pid 1633305
2023-11-15 18:51:25.634 - debug: roborock.0 (1633305) Redis Objects: Use Redis connection: 127.0.0.1:9001
2023-11-15 18:51:25.738 - debug: roborock.0 (1633305) Objects client ready ... initialize now
2023-11-15 18:51:25.739 - debug: roborock.0 (1633305) Objects create System PubSub Client
2023-11-15 18:51:25.740 - debug: roborock.0 (1633305) Objects create User PubSub Client
2023-11-15 18:51:25.946 - debug: roborock.0 (1633305) Objects client initialize lua scripts
2023-11-15 18:51:25.951 - debug: roborock.0 (1633305) Objects connected to redis: 127.0.0.1:9001
2023-11-15 18:51:26.076 - debug: roborock.0 (1633305) Redis States: Use Redis connection: 127.0.0.1:9000
2023-11-15 18:51:26.139 - debug: roborock.0 (1633305) States create System PubSub Client
2023-11-15 18:51:26.139 - debug: roborock.0 (1633305) States create User PubSub Client
2023-11-15 18:51:26.298 - debug: roborock.0 (1633305) States connected to redis: 127.0.0.1:9000
2023-11-15 18:51:26.391 - debug: roborock.0 (1633305) Plugin sentry Initialize Plugin (enabled=true)
2023-11-15 18:51:26.719 - info: roborock.0 (1633305) starting. Version 0.4.4 (non-npm: copystring/ioBroker.roborock#zeo_one) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.17.1, js-controller: 5.0.16
2023-11-15 18:51:27.718 - info: roborock.0 (1633305) MQTT initialized
2023-11-15 18:51:27.720 - debug: roborock.0 (1633305) RoomIDs debug: {}
2023-11-15 18:51:27.723 - debug: roborock.0 (1633305) arch: x64
2023-11-15 18:51:27.724 - debug: roborock.0 (1633305) platform: linux
2023-11-15 18:51:27.725 - debug: roborock.0 (1633305) System type: go2rtc_linux_amd64
2023-11-15 18:51:27.725 - debug: roborock.0 (1633305) downloadURL: https://github.com/AlexxIT/go2rtc/releases/download/v1.3.0/go2rtc_linux_amd64
2023-11-15 18:51:29.643 - debug: roborock.0 (1633305) Made ./lib/go2rtc/go2rtc_linux_amd64 executable
2023-11-15 18:51:29.712 - debug: roborock.0 (1633305) homedata successfully updated
2023-11-15 18:52:07.977 - info: tesla-motors.0 (1633170) Skip path .charge_history
2023-11-15 18:52:10.139 - info: host.iobroker "system.adapter.roborock.0" disabled
2023-11-15 18:52:10.139 - info: host.iobroker stopInstance system.adapter.roborock.0 (force=false, process=true)
2023-11-15 18:52:10.147 - info: roborock.0 (1633305) Got terminate signal TERMINATE_YOURSELF
2023-11-15 18:52:10.148 - info: roborock.0 (1633305) terminating
2023-11-15 18:52:10.149 - debug: roborock.0 (1633305) Plugin sentry destroyed
2023-11-15 18:52:10.149 - info: roborock.0 (1633305) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-11-15 18:52:10.185 - info: host.iobroker stopInstance system.adapter.roborock.0 send kill signal
2023-11-15 18:52:10.651 - info: roborock.0 (1633305) terminating
2023-11-15 18:52:10.891 - info: host.iobroker instance system.adapter.roborock.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)

2023-11-15 18:51:23.331 - info: host.iobroker "system.adapter.roborock.0" enabled
2023-11-15 18:51:23.875 - info: host.iobroker instance system.adapter.roborock.0 started with pid 1633305
2023-11-15 18:51:25.634 - debug: roborock.0 ([1633305](tel:1633305)) Redis Objects: Use Redis connection: 127.0.0.1:9001
2023-11-15 18:51:25.738 - debug: roborock.0 ([1633305](tel:1633305)) Objects client ready ... initialize now
2023-11-15 18:51:25.739 - debug: roborock.0 ([1633305](tel:1633305)) Objects create System PubSub Client
2023-11-15 18:51:25.740 - debug: roborock.0 ([1633305](tel:1633305)) Objects create User PubSub Client
2023-11-15 18:51:25.946 - debug: roborock.0 ([1633305](tel:1633305)) Objects client initialize lua scripts
2023-11-15 18:51:25.951 - debug: roborock.0 ([1633305](tel:1633305)) Objects connected to redis: 127.0.0.1:9001
2023-11-15 18:51:26.076 - debug: roborock.0 ([1633305](tel:1633305)) Redis States: Use Redis connection: 127.0.0.1:9000
2023-11-15 18:51:26.139 - debug: roborock.0 ([1633305](tel:1633305)) States create System PubSub Client
2023-11-15 18:51:26.139 - debug: roborock.0 ([1633305](tel:1633305)) States create User PubSub Client
2023-11-15 18:51:26.298 - debug: roborock.0 ([1633305](tel:1633305)) States connected to redis: 127.0.0.1:9000
2023-11-15 18:51:26.391 - debug: roborock.0 ([1633305](tel:1633305)) Plugin sentry Initialize Plugin (enabled=true)
2023-11-15 18:51:26.719 - info: roborock.0 ([1633305](tel:1633305)) starting. Version 0.4.4 (non-npm: copystring/ioBroker.roborock#zeo_one) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.17.1, js-controller: 5.0.16
2023-11-15 18:51:27.718 - info: roborock.0 ([1633305](tel:1633305)) MQTT initialized
2023-11-15 18:51:27.720 - debug: roborock.0 ([1633305](tel:1633305)) RoomIDs debug: {}
2023-11-15 18:51:27.723 - debug: roborock.0 ([1633305](tel:1633305)) arch: x64
2023-11-15 18:51:27.724 - debug: roborock.0 ([1633305](tel:1633305)) platform: linux
2023-11-15 18:51:27.725 - debug: roborock.0 ([1633305](tel:1633305)) System type: go2rtc_linux_amd64
2023-11-15 18:51:27.725 - debug: roborock.0 ([1633305](tel:1633305)) downloadURL: https://github.com/AlexxIT/go2rtc/releases/download/v1.3.0/go2rtc_linux_amd64
2023-11-15 18:51:29.643 - debug: roborock.0 ([1633305](tel:1633305)) Made ./lib/go2rtc/go2rtc_linux_amd64 executable
2023-11-15 18:51:29.712 - debug: roborock.0 ([1633305](tel:1633305)) homedata successfully updated
2023-11-15 18:52:07.977 - info: tesla-motors.0 ([1633170](tel:1633170)) Skip path .charge_history
2023-11-15 18:52:10.139 - info: host.iobroker "system.adapter.roborock.0" disabled
2023-11-15 18:52:10.139 - info: host.iobroker stopInstance system.adapter.roborock.0 (force=false, process=true)
2023-11-15 18:52:10.147 - info: roborock.0 ([1633305](tel:1633305)) Got terminate signal TERMINATE_YOURSELF
2023-11-15 18:52:10.148 - info: roborock.0 ([1633305](tel:1633305)) terminating
2023-11-15 18:52:10.149 - debug: roborock.0 ([1633305](tel:1633305)) Plugin sentry destroyed
2023-11-15 18:52:10.149 - info: roborock.0 ([1633305](tel:1633305)) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2023-11-15 18:52:10.185 - info: host.iobroker stopInstance system.adapter.roborock.0 send kill signal
2023-11-15 18:52:10.651 - info: roborock.0 ([1633305](tel:1633305)) terminating
2023-11-15 18:52:10.891 - info: host.iobroker instance system.adapter.roborock.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)`

**Comment by copystring** [comment]
I made a mistake. Please load https://github.com/copystring/ioBroker.roborock/tree/zeo_one again and post a new log

**Comment by ChrMaass** [comment]
Auch das, kein Problem. Aber ich glaube hat sich nicht viel geändert ^^

`2023-11-15 21:00:37.931 - info: host.iobroker "system.adapter.roborock.0" enabled
2023-11-15 21:00:38.706 - info: host.iobroker instance system.adapter.roborock.0 started with pid 1634256
2023-11-15 21:00:40.196 - debug: roborock.0 (1634256) Redis Objects: Use Redis connection: 127.0.0.1:9001
2023-11-15 21:00:40.294 - debug: roborock.0 (1634256) Objects client ready ... initialize now
2023-11-15 21:00:40.297 - debug: roborock.0 (1634256) Objects create System PubSub Client
2023-11-15 21:00:40.298 - debug: roborock.0 (1634256) Objects create User PubSub Client
2023-11-15 21:00:40.547 - debug: roborock.0 (1634256) Objects client initialize lua scripts
2023-11-15 21:00:40.561 - debug: roborock.0 (1634256) Objects connected to redis: 127.0.0.1:9001
2023-11-15 21:00:40.691 - debug: roborock.0 (1634256) Redis States: Use Redis connection: 127.0.0.1:9000
2023-11-15 21:00:40.778 - debug: roborock.0 (1634256) States create System PubSub Client
2023-11-15 21:00:40.779 - debug: roborock.0 (1634256) States create User PubSub Client
2023-11-15 21:00:40.913 - debug: roborock.0 (1634256) States connected to redis: 127.0.0.1:9000
2023-11-15 21:00:41.004 - debug: roborock.0 (1634256) Plugin sentry Initialize Plugin (enabled=true)
2023-11-15 21:00:41.313 - info: roborock.0 (1634256) starting. Version 0.4.4 (non-npm: copystring/ioBroker.roborock#zeo_one) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.17.1, js-controller: 5.0.16
2023-11-15 21:00:42.012 - info: roborock.0 (1634256) MQTT initialized
2023-11-15 21:00:42.013 - debug: roborock.0 (1634256) RoomIDs debug: {}
2023-11-15 21:00:42.014 - debug: roborock.0 (1634256) arch: x64
2023-11-15 21:00:42.015 - debug: roborock.0 (1634256) platform: linux
2023-11-15 21:00:42.015 - debug: roborock.0 (1634256) System type: go2rtc_linux_amd64
2023-11-15 21:00:42.015 - debug: roborock.0 (1634256) downloadURL: https://github.com/AlexxIT/go2rtc/releases/download/v1.3.0/go2rtc_linux_amd64
2023-11-15 21:00:44.680 - debug: roborock.0 (1634256) Made ./lib/go2rtc/go2rtc_linux_amd64 executable
2023-11-15 21:00:44.754 - debug: roborock.0 (1634256) homedata successfully updated`

**Comment by copystring** [comment]
Merkwürdig. Der Adapter ist vorher abgestürzt und jetzt nicht mehr.
Teste bitte nochmal den normalen release 0.4.4. Der sollte genauso wenig abstürzen. Würde aber keinen Sinn ergeben, da ich in der zeo_one branch nur etwas mehr Logging eingefügt habe.

**Comment by ChrMaass** [comment]
Stürzt tatsächlich auch nicht mehr ab 🤷🏼‍♂️ Aber das Device ist natürlich noch nicht vorhanden. Habe auch irgendwann ein Firmwareupdate des Waschtrockners durchgeführt, vielleicht hat es etwas damit zu tun. Das Device ist aber noch nicht angelegt. 

Du kannst mich gerne auch per Telegram unter @MaassIT anschreiben.

**Comment by Domi920** [comment]
Hello,
I also have a Roborock Zeo One washer dryer.
However, many objects are missing:
![image](https://github.com/copystring/ioBroker.roborock/assets/68474558/ddb1c0f8-0e26-4d88-802e-585e775b4a83)


What am I doing wrong?

Greetings Dominik

**Comment by copystring** [comment]
You're doing nothing wrong. There is no support for zeo one. It has a different kind of encryption which is very hard to decode without having such a device.

**Comment by Domi920** [comment]
How can I help you?

**Comment by copystring** [comment]
Unless you know reverse engineering and know how to sniff and decrypt encrypted mqtt and https traffic, there is not much you can do. I don't have much time to work on sniffing at the moment.

**Comment by Domi920** [comment]
Unfortunately, I am not familiar with this area.

Thanks for the information.
If I can help, I'll be ready at any time.

@ChrMaass Have you found another way to integrate?
