### ISSUE TITLE
Support for Roborock Q5 Pro

### ISSUE THREAD

**Issue by gandaneo** [copystring/ioBroker.roborock#437]
Hello everyone,

I recently became the owner of a Roborock Q5 Pro and would like to integrate it into iobroker.
Perhaps it would be possible to integrate this model into the adapter as well?
I have already created a log file:
```

2023-11-24 23:54:18.484 - debug: roborock.0 (3592452) Redis Objects: Use Redis connection: 127.0.0.1:9001
2023-11-24 23:54:18.498 - debug: roborock.0 (3592452) Objects client ready ... initialize now
2023-11-24 23:54:18.499 - debug: roborock.0 (3592452) Objects create System PubSub Client
2023-11-24 23:54:18.500 - debug: roborock.0 (3592452) Objects create User PubSub Client
2023-11-24 23:54:18.516 - debug: roborock.0 (3592452) Objects client initialize lua scripts
2023-11-24 23:54:18.519 - debug: roborock.0 (3592452) Objects connected to redis: 127.0.0.1:9001
2023-11-24 23:54:18.530 - debug: roborock.0 (3592452) Redis States: Use Redis connection: 127.0.0.1:9000
2023-11-24 23:54:18.536 - debug: roborock.0 (3592452) States create System PubSub Client
2023-11-24 23:54:18.536 - debug: roborock.0 (3592452) States create User PubSub Client
2023-11-24 23:54:18.586 - debug: roborock.0 (3592452) States connected to redis: 127.0.0.1:9000
2023-11-24 23:54:18.603 - debug: roborock.0 (3592452) Plugin sentry Initialize Plugin (enabled=true)
2023-11-24 23:54:18.606 - info: roborock.0 (3592452) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2023-11-24 23:54:18.678 - info: roborock.0 (3592452) starting. Version 0.4.4 in /opt/iobroker/node_modules/iobroker.roborock, node: v19.3.0, js-controller: 5.0.16
2023-11-24 23:54:19.150 - info: roborock.0 (3592452) MQTT initialized
2023-11-24 23:54:19.150 - debug: roborock.0 (3592452) RoomIDs debug: {"15138200":"Küche","15138209":"Esszimmer"}
2023-11-24 23:54:19.150 - error: roborock.0 (3592452) The model roborock.vacuum.a72 is not supported. Get in touch with the dev to get this robot supported.
2023-11-24 23:54:19.300 - error: roborock.0 (3592452) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-11-24 23:54:19.300 - error: roborock.0 (3592452) unhandled promise rejection: Cannot find module './undefined'
Require stack:
- /opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js
- /opt/iobroker/node_modules/iobroker.roborock/main.js
2023-11-24 23:54:19.301 - error: roborock.0 (3592452) Error: Cannot find module './undefined'
Require stack:
- /opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js
- /opt/iobroker/node_modules/iobroker.roborock/main.js
at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
at Module._load (node:internal/modules/cjs/loader:885:27)
at Module.require (node:internal/modules/cjs/loader:1105:19)
at require (node:internal/modules/cjs/helpers:103:18)
at new vacuum (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:45:31)
at /opt/iobroker/node_modules/iobroker.roborock/main.js:208:29
2023-11-24 23:54:19.301 - error: roborock.0 (3592452) Exception-Code: MODULE_NOT_FOUND: Cannot find module './undefined'
Require stack:
- /opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js
- /opt/iobroker/node_modules/iobroker.roborock/main.js
2023-11-24 23:54:19.303 - info: roborock.0 (3592452) terminating
2023-11-24 23:54:19.304 - debug: roborock.0 (3592452) Plugin sentry destroyed
2023-11-24 23:54:19.304 - warn: roborock.0 (3592452) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-11-24 23:54:19.805 - info: roborock.0 (3592452) terminating
2023-11-24 23:54:19.839 - error: host.iobroker instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-11-24 23:54:19.839 - info: host.iobroker Restart adapter system.adapter.roborock.0 because enabled
```

Many thanks in advance.

**Comment by copystring** [comment]
Please test https://github.com/copystring/ioBroker.roborock/tree/dev and let me know if anything is missing. Most likely, some commands would be missing.
If there are any errors or warnings, post a new Debuglog. Thank you.

**Comment by copystring** [comment]
Very odd error. Would you please reinstall the adapter once and test again?
