### ISSUE TITLE
Keine Datenpunkte / HomeData-Datenpunkt wird befüllt

### ISSUE THREAD

**Issue by KoMa1978** [copystring/ioBroker.roborock#439]
Hallo zusammen,

ich habe heute einen Roborock Q Revo (Firmware 02.15.82) in Betrieb genommen und auch an ioBroker angebunden.
Im Prinzip funktioniert die Abfrage auch, die Datenpunkte "HomeData" und "UserData" werden mit JSON befüllt.

Allerdings werden keine Datenpunkte zum Steuern/Auslesen unterhalb von "Devices" erstellt.
![image](https://github.com/copystring/ioBroker.roborock/assets/57285166/530c1fd1-1309-455d-97f4-34214dab3f28)
Was kann ich hier tun, um eine Lösung zu finden?

Es kommt regelmäßig ein OK:
2023-11-26 14:26:32.256 - debug: roborock.0 (8538) homedata successfully updated

Merkwürdig finde ich folgende Logs:
2023-11-26 14:25:29.971 - debug: roborock.0 (8538) RoomIDs debug: {}

Aber es sieht eigentlich gut aus (er reinigt aktuell):
2023-11-26 14:28:25.338 - debug: roborock.0 (8538) dps debug: {"id":307531,"result":[{"msg_ver":2,"msg_seq":4354,"state":5,"battery":94,"clean_time":733,"clean_area":25670000,"error_code":0,"map_present":1,"in_cleaning":1,"in_returning":0,"in_fresh_state":0,"lab_status":1,"water_box_status":1,"fan_power":101,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":201,"distance_off":0,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":1,"is_exploring":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":8,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":0,"mop_mode":300,"in_warmup":0,"back_type":-1,"wash_phase":0,"wash_ready":0,"wash_status":768,"debug_mode":0,"collision_avoid_status":1,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0,"dry_status":0,"rdt":0,"clean_percent":11,"rss":2,"dss":681,"common_status":0,"corner_clean_mode":0,"events":[],"switch_status":1,"last_clean_t":1700993849}]}

Adapter ist heute aus dem DEV-Tree installiert.

**Comment by copystring** [comment]
Bitte ein vollständiges Debuglog anhängen

**Comment by KoMa1978** [comment]
Ein xxxXXXxxx im Log kommt von mir. Ich hoffe da ist nicht kritisches mehr drin.

[debug.log](https://github.com/copystring/ioBroker.roborock/files/13467085/debug.log)

**Comment by copystring** [comment]
Es wird gar kein Roboter erkannt. Hast du einen Roboter in der Roborock App?

**Comment by KoMa1978** [comment]
Ja in der App ist einer und im Log taucht auch eine SN auf die ich mit xxxXXXxxx überschrieben habe. 

Ich nutze nicht den Master Account (den betreibt ein Kollege). Mir wurde der Roboter freigegeben und den Account den ich in der App nutze den nutze ich auch in iobroker

**Comment by KoMa1978** [comment]
Ne das hängt nicht mit der Freigabe zusammen. Geht auch mit dem Master Account nicht

**Comment by copystring** [comment]
> Ne das hängt nicht mit der Freigabe zusammen. Geht auch mit dem Master Account nicht

Das kann eigentlich nicht sein. Mit dem Hauptkonto muss es gehen. Aber egal, ich habe zufälligerweise unabhängig von deinem Problem einige Fehler in der dev behoben.
Probier bitte die aktuelle dev nochmal aus.

**Comment by KoMa1978** [comment]
Grad neu installiert und geht ;-)

Danke dir!!!

**Comment by copystring** [comment]
Gern. Wenn noch was fehlen sollte, dann hier nochmal melden.

**Comment by KoMa1978** [comment]
Hmmm jetzt hat er zwar die Objekte angelegt, stürzt aber sofort und Regelmäßig ab:

[debug.log](https://github.com/copystring/ioBroker.roborock/files/13500268/debug.log)

**Comment by copystring** [comment]
Probiere die neue dev bitte erneut aus. Es sollte behoben sein.

**Comment by KoMa1978** [comment]
Jetzt holt er einige Werte stürtzt dann aber wieder ab:


023-11-29 23:00:59.832 - info: roborock.0 (15415) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
--
2023-11-29 23:00:59.918 - info: host.iobroker01 stopInstance system.adapter.roborock.0 send kill signal
2023-11-29 23:01:00.333 - info: roborock.0 (15415) terminating
2023-11-29 23:01:00.340 - error: roborock.0 (15415) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-11-29 23:01:00.340 - error: roborock.0 (15415) unhandled promise rejection: Connection is closed.
2023-11-29 23:01:00.340 - error: roborock.0 (15415) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:628:26)
at Socket.emit (node:events:513:28)
at TCP. (node:net:301:12)
2023-11-29 23:01:00.341 - error: roborock.0 (15415) Connection is closed.
2023-11-29 23:01:00.341 - error: roborock.0 (15415) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-11-29 23:01:00.342 - error: roborock.0 (15415) unhandled promise rejection: Connection is closed.
2023-11-29 23:01:00.342 - error: roborock.0 (15415) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:628:26)
at Socket.emit (node:events:513:28)
at TCP. (node:net:301:12)
2023-11-29 23:01:00.342 - error: roborock.0 (15415) Connection is closed.
2023-11-29 23:01:00.395 - info: host.iobroker01 instance system.adapter.roborock.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)

**Comment by copystring** [comment]
Welches System? Ein Raspberry Pi?

**Comment by copystring** [comment]
OK. Sehr merkwürdiger Fehler. Vielleicht hilft ein Neustart

**Comment by KoMa1978** [comment]
OK ... Deinstallation des Adapters (Verzeichnis im Dateisystem gelöscht), Neustart des System und Neuinstallation des Adapters.

Seitdem läuft er (seit ca 1h), Die Daten unter "deviceinfo" werden befüllt, die anderen aber komischerweise nicht.
In der App (mit gleichem Account) sind diese Daten befüllt.

![image](https://github.com/copystring/ioBroker.roborock/assets/57285166/4b219996-bd59-42d6-9156-c40203abd053)

Für die Anzahl an Datenpunkten im Roboter sehe ich auch ziemlich wenig MQTTs Traffic vom ioBroker in Richtung Internet.

**Comment by copystring** [comment]
> Hmmm so ganz richtig sieht das noch nicht aus:
> ![image](https://github.com/copystring/ioBroker.roborock/assets/57285166/a6351698-d14c-4941-9bd5-bbed614b4425)
> 

Das ist normal. Der Prozess von go2rtc muss gekillt werden, wenn dieser noch läuft. https://github.com/copystring/ioBroker.roborock/blob/cb577bd227aeff14a1e64cea413aa5736836840d/main.js#L768

Den Rest der Fehler von weiter oben kann ich mir heute Abend angucken.

**Comment by KoMa1978** [comment]
Ich habe eben die Instanz gestoppt, in den Objekten den gesamten Datenbaum für die Roboter ID gelöscht und die Instanz wieder gestartet.

Der gesamte Baum wird sofort wieder erstellt, aber Werte werden aber wieder nur in "deviceInfo" geschrieben.
Das aber auch sofort. In allen anderen Bereichen kommen keine Werte an, nur (null) etc.

Ich habe aber eben folgendes im Debug entdeckt:
2023-12-01 17:14:55.987 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_fw_features
2023-12-01 17:14:55.988 - debug: roborock.0 (6027) Firmware features request
2023-12-01 17:14:56.001 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.001 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_multi_maps_list
2023-12-01 17:14:56.046 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.047 - debug: roborock.0 (6027) Latest data requested
2023-12-01 17:14:56.047 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_status
2023-12-01 17:14:56.094 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.095 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_room_mapping
2023-12-01 17:14:56.138 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.139 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_consumable
2023-12-01 17:14:56.186 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.187 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_network_info
2023-12-01 17:14:56.230 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.230 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_server_timer
2023-12-01 17:14:56.231 - debug: roborock.0 (6027) get_server_timer: " + {}
2023-12-01 17:14:56.231 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_timer
2023-12-01 17:14:56.231 - debug: roborock.0 (6027) get_timer: "{}
2023-12-01 17:14:56.231 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_carpet_mode
2023-12-01 17:14:56.274 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.275 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.275 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.276 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_carpet_clean_mode
2023-12-01 17:14:56.322 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.323 - debug: roborock.0 (6027) getParameter for xxxXXXxxx: get_water_box_custom_mode
2023-12-01 17:14:56.366 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.
2023-12-01 17:14:56.414 - debug: roborock.0 (6027) Not sending request. Device xxxXXXxxx is offline.

Ja, der Sauger fährt aktuell nicht, aber er ist online. Ich könnte ihn über die App auch starten.

**Comment by KoMa1978** [comment]
Klar …

die xxxXXXxxx kommen wieder von mir. Die asiatischen Zeichen weiß ich nicht ob die richtig sind, ich hab überall deutsch eingestellt. Komischerweise werden aber trotz meines „Tricks“ 3 Felder unter consumables (125, 126 , 127 und cleaning_brush_work_times) nicht gefüllt, aber das ist eine andere Frage für später:


{"id":5159559,"name":"My Home","lon":null,"lat":null,"geoName":null,"products":[{"id":"xxxXXXxxx","name":"Roborock Q Revo","model":"roborock.vacuum.a75","iconUrl":null,"attribute":null,"capability":0,"category":"robot.vacuum.cleaner","schema":[{"id":"101","name":"rpc_request","code":"rpc_request","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"102","name":"rpc_response","code":"rpc_response","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"120","name":"错误代码","code":"error_code","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"121","name":"设备状态","code":"state","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"122","name":"设备电量","code":"battery","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"123","name":"清扫模式","code":"fan_power","mode":"rw","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"124","name":"拖地模式","code":"water_box_mode","mode":"rw","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"125","name":"主刷寿命","code":"main_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"126","name":"边刷寿命","code":"side_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"127","name":"滤网寿命","code":"filter_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"128","name":"额外状态","code":"additional_props","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"130","name":"完成事件","code":"task_complete","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"131","name":"电量不足任务取消","code":"task_cancel_low_power","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"132","name":"运动中任务取消","code":"task_cancel_in_motion","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"133","name":"充电状态","code":"charge_status","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"134","name":"烘干状态","code":"drying_status","mode":"ro","type":"RAW","property":null,"desc":null}]}],"devices":[],"receivedDevices":[{"duid":"xxxXXXxxx","name":"Robbie","attribute":null,"activeTime":1700987603,"localKey":"xxxXXXxxx","runtimeEnv":null,"timeZoneId":"Europe/Berlin","iconUrl":"","productId":"ldHlB6hwVPMvdm6AdkxJv","lon":null,"lat":null,"share":true,"shareTime":1700988017,"online":true,"fv":"02.16.98","pv":"1.0","roomId":15220223,"tuyaUuid":null,"tuyaMigrated":false,"extra":null,"setting":null,"sn":"xxxXXXxxx","featureSet":"2238601361260287","newFeatureSet":"00000000081AFFFE","deviceStatus":{"120":0,"121":8,"122":100,"123":102,"124":203,"125":97,"126":97,"127":93,"128":0,"133":1,"134":0},"silentOtaSwitch":false,"f":false}],"rooms":[]}

**Comment by KoMa1978** [comment]
Grad gemacht. Deinstalliert und neu installiert aber leider wieder das alte Verhalten.

**Comment by KoMa1978** [comment]
Klar!

Anbei die Logs, einmal eingeloggt mit dem Haupt-Account und einmal mit dem eigentlichen (geteilten) Account.

Ich habe in beiden Fällen so lange gewartet, bis er anfangen wollte, die Daten abzurufen.

[debug_shared.log](https://github.com/copystring/ioBroker.roborock/files/13539472/debug_shared.log)
[debug_haupt.log](https://github.com/copystring/ioBroker.roborock/files/13539474/debug_haupt.log)

**Comment by copystring** [comment]
Den Fehler kenne ich bereits, aber aktuell gibts ein grundsätzliches Problem. Anscheinend begrenzt Roborock die Anfragen des Adapters oder von meinem Account. 
Vielleicht magst du mal in dein log gucken. Bei mir tauchen dort einige Timeouts auf. Ist das bei dir auch so?

**Comment by copystring** [comment]
Der S8 und Q Revo scheinen gar keine Reinigungsbürste zu haben bzw. wird dies nicht in der App angezeigt. Daher habe ich cleaning_brush_work_times entfernt. Du müsstest nur noch den Datenpunkt aus ioBroker löschen.
Die anderen Werte werden nun in der dev entsprechend aktualisiert.
Dass die nur zahlen sind, liegt an Roborock. Darauf habe ich keinen Einfluss.

**Comment by copystring** [comment]
OK. Kann also geschlossen werden?

**Comment by KoMa1978** [comment]
Jo das können wir. Vielen Dank!
