### ISSUE TITLE
Adapter startet nicht mehr

### ISSUE THREAD

**Issue by mproper23** [copystring/ioBroker.roborock#459]
Hallo,

habe habe die 0.4.4 installiert. Adapter wird kurz grün dann kommt 

```
<html><body>
<!--StartFragment-->
roborock.0 | 2023-12-17 13:19:31.263 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
roborock.0 | 2023-12-17 13:19:31.263 | info | terminating
roborock.0 | 2023-12-17 13:19:31.257 | error | Cannot read properties of null (reading 'devices')
roborock.0 | 2023-12-17 13:19:31.257 | error | TypeError: Cannot read properties of null (reading 'devices')     at roborock_mqtt_connector.initUser (c:\iobroker\node_modules\iobroker.roborock\lib\roborock_mqtt_connector.js:90:22)     at c:\iobroker\node_modules\iobroker.roborock\main.js:184:25
roborock.0 | 2023-12-17 13:19:31.255 | error | unhandled promise rejection: Cannot read properties of null (reading 'devices')
roborock.0 | 2023-12-17 13:19:31.255 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
roborock.0 | 2023-12-17 13:19:30.483 | info | starting. Version 0.4.4 in c:/iobroker/node_modules/iobroker.roborock, node: v18.18.2, js-controller: 5.0.16

<!--EndFragment-->
</body>
</html>
```

Habe auch schon mal sowohl Instanz als auch Adapter komplett gelöscht. Es wird der Ordner Devices angelegt aber nicht befüllt

**Comment by copystring** [comment]
https://github.com/copystring/ioBroker.roborock/issues/458
