### ISSUE TITLE
Restart-loop on DEV

### ISSUE THREAD

**Issue by trollvottel** [copystring/ioBroker.roborock#471]
Today somehow the adapter refuses to start and keep running. No idea why.

Happy new year btw :)
```
2024-01-01 11:00:25.395  - info: host.iobroker instance system.adapter.roborock.0 started with pid 964257
--
2024-01-01 11:00:26.362  - info:  roborock.0 (964257) Plugin sentry Sentry Plugin disabled for this  process because sending of statistic data is disabled for the system
2024-01-01 11:00:26.417  - info:  roborock.0 (964257) starting. Version 0.4.4 (non-npm:  copystring/ioBroker.roborock#dev) in  /opt/iobroker/node_modules/iobroker.roborock, node: v18.17.1,  js-controller: 5.0.17
2024-01-01 11:00:32.209  - info: roborock.0 (964257) MQTT initialized
2024-01-01 11:00:59.450  - info:  roborock.0 (964257) State value to set for  "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294834.items.0.id"  has to be type "string" but received type "number"
2024-01-01 11:00:59.450  - info:  roborock.0 (964257) State value to set for  "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294834.items.0.finishDpIds"  has to be type "string" but received type "object"
2024-01-01 11:00:59.460  - info:  roborock.0 (964257) State value to set for  "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294825.items.0.id"  has to be type "string" but received type "number"
2024-01-01 11:00:59.460  - info:  roborock.0 (964257) State value to set for  "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294825.items.0.finishDpIds"  has to be type "string" but received type "object"
2024-01-01 11:00:59.465  - error:  roborock.0 (964257) Failed to execute get_status on robot  4yQfEyXcIbtKILL7DtxjdA Unsupported attribute: distance_off of get_status  with value 0. Please contact the dev to add the newly found attribute  of your robot.
2024-01-01 11:00:59.466  - error:  roborock.0 (964257) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2024-01-01 11:00:59.466  - error: roborock.0 (964257) unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
2024-01-01 11:00:59.466  - error: roborock.0 (964257) TypeError: Cannot read properties of undefined (reading 'captureException')
at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:1021:44)
at runNextTicks (node:internal/process/task_queues:60:5)
at process.processImmediate (node:internal/timers:447:9)
2024-01-01 11:00:59.466  - error: roborock.0 (964257) Cannot read properties of undefined (reading 'captureException')
2024-01-01 11:00:59.467  - error:  roborock.0 (964257) Failed to execute get_status on robot  4yQfEyXcIbtKILL7DtxjdA Unsupported attribute: camera_status of  get_status with value 1. Please contact the dev to add the newly found  attribute of your robot.
2024-01-01 11:00:59.467  - error:  roborock.0 (964257) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2024-01-01 11:00:59.467  - error: roborock.0 (964257) unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
2024-01-01 11:00:59.467  - error: roborock.0 (964257) TypeError: Cannot read properties of undefined (reading 'captureException')
at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:1021:44)
at runNextTicks (node:internal/process/task_queues:60:5)
at process.processImmediate (node:internal/timers:447:9)
2024-01-01 11:00:59.467  - error: roborock.0 (964257) Cannot read properties of undefined (reading 'captureException')
2024-01-01 11:00:59.468  - info: roborock.0 (964257) terminating
2024-01-01 11:00:59.468  - warn: roborock.0 (964257) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-01 11:00:59.470  - error:  roborock.0 (964257) Failed to execute get_status on robot  4yQfEyXcIbtKILL7DtxjdA Unsupported attribute: kct of get_status with  value 0. Please contact the dev to add the newly found attribute of your  robot.
2024-01-01 11:00:59.470  - error:  roborock.0 (964257) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block, or  by rejecting a promise which was not handled with .catch().
2024-01-01 11:00:59.470  - error: roborock.0 (964257) unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
2024-01-01 11:00:59.470  - error: roborock.0 (964257) TypeError: Cannot read properties of undefined (reading 'captureException')
at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:1021:44)
at runNextTicks (node:internal/process/task_queues:60:5)
at process.processImmediate (node:internal/timers:447:9)
2024-01-01 11:00:59.470  - error: roborock.0 (964257) Cannot read properties of undefined (reading 'captureException')
2024-01-01 11:00:59.470  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.478  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.479  - info:  roborock.0 (964257) State value to set for  "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294803.items.0.id"  has to be type "string" but received type "number"
2024-01-01 11:00:59.479  - info:  roborock.0 (964257) State value to set for  "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294803.items.0.finishDpIds"  has to be type "string" but received type "object"
2024-01-01 11:00:59.494  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.539  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.544  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.555  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.614  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.630  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.649  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.713  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.731  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.757  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.817  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.835  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.855  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.916  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.934  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.951  - warn: roborock.0 (964257) setTimeout called, but adapter is shutting down
2024-01-01 11:00:59.968  - info: roborock.0 (964257) terminating
2024-01-01 11:01:00.005  - error: host.iobroker instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
```

**Comment by trollvottel** [comment]
Eben die DEV aktualisiert, seitdem startet er wieder. Ich lass das Ticket trotzdem mal offen, vielleicht siehst Du ja noch was Brauchbares im Log.

**Comment by trollvottel** [comment]
Another restart-loop:

`2024-01-02 02:07:24.465 - warn: roborock.0 (964714) MQTT connection close.
2024-01-02 02:07:24.467 - warn: roborock.0 (964714) MQTT connection reconnect.
2024-01-02 03:54:00.542 - warn: roborock.0 (964714) Unable to decode message for 4yQfEyXcIbtKILL7DtxjdA. The the device is most likely offline.
2024-01-02 03:54:40.208 - warn: roborock.0 (964714) Unable to decode message for 4yQfEyXcIbtKILL7DtxjdA. The the device is most likely offline.
2024-01-02 05:07:24.453 - warn: roborock.0 (964714) MQTT connection close.
2024-01-02 05:07:24.453 - warn: roborock.0 (964714) MQTT connection reconnect.
2024-01-02 08:07:24.466 - warn: roborock.0 (964714) MQTT connection close.
2024-01-02 08:07:24.467 - warn: roborock.0 (964714) MQTT connection reconnect.
2024-01-02 11:07:24.466 - warn: roborock.0 (964714) MQTT connection close.
2024-01-02 11:07:24.466 - warn: roborock.0 (964714) MQTT connection reconnect.
2024-01-02 14:07:24.455 - warn: roborock.0 (964714) MQTT connection close.
2024-01-02 14:07:24.455 - warn: roborock.0 (964714) MQTT connection reconnect.
2024-01-02 14:33:34.995 - warn: roborock.0 (964714) Failed to execute load_multi_map on robot 4yQfEyXcIbtKILL7DtxjdA Error: Local request with id 16526 with method load_multi_map timed out after 10 seconds for response.102
2024-01-02 14:34:34.989 - warn: roborock.0 (964714) Failed to execute load_multi_map on robot 4yQfEyXcIbtKILL7DtxjdA Error: Local request with id 16537 with method load_multi_map timed out after 10 seconds for response.102
2024-01-02 15:00:35.037 - warn: roborock.0 (964714) Failed to execute load_multi_map on robot 4yQfEyXcIbtKILL7DtxjdA Error: Local request with id 16819 with method load_multi_map timed out after 10 seconds for response.102
2024-01-02 15:31:35.051 - warn: roborock.0 (964714) Failed to execute load_multi_map on robot 4yQfEyXcIbtKILL7DtxjdA Error: Local request with id 17193 with method load_multi_map timed out after 10 seconds for response.102
2024-01-02 15:46:35.059 - warn: roborock.0 (964714) Failed to execute load_multi_map on robot 4yQfEyXcIbtKILL7DtxjdA Error: Local request with id 17365 with method load_multi_map timed out after 10 seconds for response.102
2024-01-02 15:47:35.012 - warn: roborock.0 (964714) Failed to execute load_multi_map on robot 4yQfEyXcIbtKILL7DtxjdA Error: Local request with id 17376 with method load_multi_map timed out after 10 seconds for response.102
2024-01-02 15:48:35.100 - warn: roborock.0 (964714) Failed to execute load_multi_map on robot 4yQfEyXcIbtKILL7DtxjdA Error: Local request with id 17388 with method load_multi_map timed out after 10 seconds for response.102
2024-01-02 15:48:35.187 - warn: roborock.0 (964714) Failed to execute get_consumable on robot 4yQfEyXcIbtKILL7DtxjdA Error: Local request with id 17392 with method get_consumable timed out after 10 seconds for response.102
2024-01-02 15:49:25.019 - error: roborock.0 (964714) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-02 15:49:25.019 - error: roborock.0 (964714) unhandled promise rejection: Cannot read properties of undefined (reading 'code')
2024-01-02 15:49:25.020 - error: roborock.0 (964714) TypeError: Cannot read properties of undefined (reading 'code')
2024-01-02 15:49:25.020 - error: roborock.0 (964714) Cannot read properties of undefined (reading 'code')
2024-01-02 15:49:25.021 - info: roborock.0 (964714) terminating
2024-01-02 15:49:25.022 - warn: roborock.0 (964714) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-02 15:49:25.022 - warn: roborock.0 (964714) setTimeout called, but adapter is shutting down
2024-01-02 15:49:25.074 - warn: roborock.0 (964714) setTimeout called, but adapter is shutting down
2024-01-02 15:49:25.090 - warn: roborock.0 (964714) setTimeout called, but adapter is shutting down
2024-01-02 15:49:25.141 - warn: roborock.0 (964714) setTimeout called, but adapter is shutting down
2024-01-02 15:49:25.324 - warn: roborock.0 (964714) setTimeout called, but adapter is shutting down
2024-01-02 15:49:25.329 - warn: roborock.0 (964714) setTimeout called, but adapter is shutting down
2024-01-02 15:49:25.377 - warn: roborock.0 (964714) setTimeout called, but adapter is shutting down
2024-01-02 15:49:25.383 - warn: roborock.0 (964714) setTimeout called, but adapter is shutting down
2024-01-02 15:49:25.390 - warn: roborock.0 (964714) setTimeout called, but adapter is shutting down
2024-01-02 15:49:25.523 - info: roborock.0 (964714) terminating
2024-01-02 15:49:25.567 - error: host.iobroker instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-02 15:49:25.567 - info: host.iobroker Restart adapter system.adapter.roborock.0 because enabled
2024-01-02 15:49:55.641 - info: host.iobroker instance system.adapter.roborock.0 started with pid 1047699
2024-01-02 15:49:56.349 - info: roborock.0 (1047699) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2024-01-02 15:49:56.387 - info: roborock.0 (1047699) starting. Version 0.4.4 (non-npm: copystring/ioBroker.roborock#dev) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.17.1, js-controller: 5.0.17
2024-01-02 15:50:02.027 - info: roborock.0 (1047699) MQTT initialized
2024-01-02 15:50:28.503 - info: roborock.0 (1047699) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294834.items.0.id" has to be type "string" but received type "number"
2024-01-02 15:50:28.503 - info: roborock.0 (1047699) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294834.items.0.finishDpIds" has to be type "string" but received type "object"
2024-01-02 15:50:28.513 - info: roborock.0 (1047699) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294825.items.0.id" has to be type "string" but received type "number"
2024-01-02 15:50:28.514 - info: roborock.0 (1047699) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294825.items.0.finishDpIds" has to be type "string" but received type "object"
2024-01-02 15:50:28.556 - info: roborock.0 (1047699) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294803.items.0.id" has to be type "string" but received type "number"
2024-01-02 15:50:28.556 - info: roborock.0 (1047699) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294803.items.0.finishDpIds" has to be type "string" but received type "object"
2024-01-02 15:50:28.560 - error: roborock.0 (1047699) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-02 15:50:28.560 - error: roborock.0 (1047699) unhandled promise rejection: Cannot read properties of undefined (reading 'code')
2024-01-02 15:50:28.560 - error: roborock.0 (1047699) TypeError: Cannot read properties of undefined (reading 'code')
2024-01-02 15:50:28.560 - error: roborock.0 (1047699) Cannot read properties of undefined (reading 'code')
2024-01-02 15:50:28.561 - info: roborock.0 (1047699) terminating
2024-01-02 15:50:28.561 - warn: roborock.0 (1047699) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-02 15:50:28.607 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.608 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.626 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.648 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.708 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.723 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.738 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.812 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.829 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.845 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.904 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.920 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.934 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:28.991 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:29.011 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:29.026 - warn: roborock.0 (1047699) setTimeout called, but adapter is shutting down
2024-01-02 15:50:29.061 - info: roborock.0 (1047699) terminating
2024-01-02 15:50:29.094 - error: host.iobroker instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-02 15:50:29.094 - info: host.iobroker Restart adapter system.adapter.roborock.0 because enabled
2024-01-02 15:50:59.134 - info: host.iobroker instance system.adapter.roborock.0 started with pid 1047763
2024-01-02 15:50:59.845 - info: roborock.0 (1047763) Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
2024-01-02 15:50:59.889 - info: roborock.0 (1047763) starting. Version 0.4.4 (non-npm: copystring/ioBroker.roborock#dev) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.17.1, js-controller: 5.0.17
2024-01-02 15:51:05.623 - info: roborock.0 (1047763) MQTT initialized
2024-01-02 15:51:32.118 - info: roborock.0 (1047763) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294834.items.0.id" has to be type "string" but received type "number"
2024-01-02 15:51:32.126 - info: roborock.0 (1047763) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294834.items.0.finishDpIds" has to be type "string" but received type "object"
2024-01-02 15:51:32.132 - info: roborock.0 (1047763) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294825.items.0.id" has to be type "string" but received type "number"
2024-01-02 15:51:32.134 - info: roborock.0 (1047763) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294825.items.0.finishDpIds" has to be type "string" but received type "object"
2024-01-02 15:51:32.150 - info: roborock.0 (1047763) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294803.items.0.id" has to be type "string" but received type "number"
2024-01-02 15:51:32.151 - info: roborock.0 (1047763) State value to set for "roborock.0.Devices.4yQfEyXcIbtKILL7DtxjdA.programs.1294803.items.0.finishDpIds" has to be type "string" but received type "object"
2024-01-02 15:51:32.155 - error: roborock.0 (1047763) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-01-02 15:51:32.156 - error: roborock.0 (1047763) unhandled promise rejection: Cannot read properties of undefined (reading 'code')
2024-01-02 15:51:32.156 - error: roborock.0 (1047763) TypeError: Cannot read properties of undefined (reading 'code')
2024-01-02 15:51:32.156 - error: roborock.0 (1047763) Cannot read properties of undefined (reading 'code')
2024-01-02 15:51:32.158 - info: roborock.0 (1047763) terminating
2024-01-02 15:51:32.158 - warn: roborock.0 (1047763) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-01-02 15:51:32.242 - warn: roborock.0 (1047763) setTimeout called, but adapter is shutting down
2024-01-02 15:51:32.260 - warn: roborock.0 (1047763) setTimeout called, but adapter is shutting down
2024-01-02 15:51:32.270 - warn: roborock.0 (1047763) setTimeout called, but adapter is shutting down
2024-01-02 15:51:32.298 - warn: roborock.0 (1047763) setTimeout called, but adapter is shutting down
2024-01-02 15:51:32.345 - warn: roborock.0 (1047763) setTimeout called, but adapter is shutting down
2024-01-02 15:51:32.351 - warn: roborock.0 (1047763) setTimeout called, but adapter is shutting down
2024-01-02 15:51:32.358 - warn: roborock.0 (1047763) setTimeout called, but adapter is shutting down
2024-01-02 15:51:32.405 - warn: roborock.0 (1047763) setTimeout called, but adapter is shutting down
2024-01-02 15:51:32.659 - info: roborock.0 (1047763) terminating
2024-01-02 15:51:32.691 - error: host.iobroker instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-01-02 15:51:32.691 - info: host.iobroker Restart adapter system.adapter.roborock.0 because enabled
2024-01-02 15:51:32.691 - warn: host.iobroker Do not restart adapter system.adapter.roborock.0 because restart loop detected
`

**Comment by copystring** [comment]
Does the dev version still work?

**Comment by trollvottel** [comment]
Haven't updated in the last 2 days. Should I?

**Comment by copystring** [comment]
I thought you have 0.5.1 installed

**Comment by trollvottel** [comment]
I've now manually restarted and it works again. But I guess it will break again after some time.

**Comment by trollvottel** [comment]
Oh, there was a release? Wonderful, will try that!

**Comment by copystring** [comment]
Well, the release is the same as the latest dev. I don't think it makes a difference

**Comment by trollvottel** [comment]
I know the error message from the log it not very helpful :(

**Comment by copystring** [comment]
Does the latest dev make a difference?

**Comment by trollvottel** [comment]
Just installed it, will report during the week. For the next to days, everything was already vacuumed today :)

**Comment by trollvottel** [comment]
Updated to v0.5.4 and now restart loop again :(

**Comment by trollvottel** [comment]
`<html><body>

2024-02-03 17:59:11.641  - error:  roborock.0 (1749190) Unhandled promise rejection. This error originated  either by throwing inside of an async function without a catch block,  or by rejecting a promise which was not handled with .catch().
--
2024-02-03 17:59:11.641  - error: roborock.0 (1749190) unhandled promise rejection: Cannot read properties of undefined (reading 'code')
2024-02-03 17:59:11.643  - error: roborock.0 (1749190) TypeError: Cannot read properties of undefined (reading 'code')
at /opt/iobroker/node_modules/iobroker.roborock/lib/message.js:178:16
at new Promise ()
at message.resolve102Message (/opt/iobroker/node_modules/iobroker.roborock/lib/message.js:177:10)
at EventEmitter.listener102 (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:120:49)
at EventEmitter.emit (/opt/iobroker/node_modules/eventemitter2/lib/eventemitter2.js:1047:22)
at Socket. (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:79:10)
at Socket.emit (node:events:514:28)
at Socket.emit (node:domain:489:12)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
2024-02-03 17:59:11.643  - error: roborock.0 (1749190) Cannot read properties of undefined (reading 'code')
2024-02-03 17:59:11.648  - info: roborock.0 (1749190) terminating
2024-02-03 17:59:11.649  - warn: roborock.0 (1749190) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-02-03 17:59:11.680  - warn: roborock.0 (1749190) setTimeout called, but adapter is shutting down
2024-02-03 17:59:11.740  - warn: roborock.0 (1749190) setTimeout called, but adapter is shutting down
2024-02-03 17:59:11.740  - warn: roborock.0 (1749190) setTimeout called, but adapter is shutting down
2024-02-03 17:59:11.753  - warn: roborock.0 (1749190) setTimeout called, but adapter is shutting down
2024-02-03 17:59:11.807  - warn: roborock.0 (1749190) setTimeout called, but adapter is shutting down
2024-02-03 17:59:12.122  - warn: roborock.0 (1749190) setTimeout called, but adapter is shutting down
2024-02-03 17:59:12.145  - warn: roborock.0 (1749190) setTimeout called, but adapter is shutting down
2024-02-03 17:59:12.151  - info: roborock.0 (1749190) terminating
2024-02-03 17:59:12.151  - warn: roborock.0 (1749190) redis get roborock.0.HomeData, error - DB closed
2024-02-03 17:59:12.153  - warn: roborock.0 (1749190) redis get roborock.0.HomeData, error - Connection is closed.
2024-02-03 17:59:12.153  - warn: roborock.0 (1749190) setTimeout called, but adapter is shutting down
2024-02-03 17:59:12.200  - error:  host.iobroker Caught by controller[1]: This error originated either by  throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch(). The promise  rejected with the reason:
2024-02-03 17:59:12.200  - error: host.iobroker Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'code')
2024-02-03 17:59:12.200  - error: host.iobroker Caught by controller[2]:     at /opt/iobroker/node_modules/iobroker.roborock/lib/message.js:178:16
2024-02-03 17:59:12.200  - error: host.iobroker Caught by controller[2]:     at new Promise ()
2024-02-03 17:59:12.200  - error:  host.iobroker Caught by controller[2]:     at message.resolve102Message  (/opt/iobroker/node_modules/iobroker.roborock/lib/message.js:177:10)
2024-02-03 17:59:12.200  - error:  host.iobroker Caught by controller[2]:     at EventEmitter.listener102  (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:120:49)
2024-02-03 17:59:12.200  - error:  host.iobroker Caught by controller[2]:     at EventEmitter.emit  (/opt/iobroker/node_modules/eventemitter2/lib/eventemitter2.js:1047:22)
2024-02-03 17:59:12.200  - error: host.iobroker Caught by controller[2]:     at Socket. (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:79:10)
2024-02-03 17:59:12.200  - error: host.iobroker Caught by controller[2]:     at Socket.emit (node:events:514:28)
2024-02-03 17:59:12.200  - error: host.iobroker Caught by controller[2]:     at Socket.emit (node:domain:489:12)
2024-02-03 17:59:12.200  - error: host.iobroker Caught by controller[2]:     at addChunk (node:internal/streams/readable:324:12)
2024-02-03 17:59:12.200  - error: host.iobroker Caught by controller[2]:     at readableAddChunk (node:internal/streams/readable:297:9)
2024-02-03 17:59:12.200  - error: host.iobroker instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2024-02-03 17:59:12.200  - info: host.iobroker Restart adapter system.adapter.roborock.0 because enabled
2024-02-03 17:59:12.200  - warn: host.iobroker Do not restart adapter system.adapter.roborock.0 because restart loop detected


</body>
</html>`

**Comment by copystring** [comment]
Das ist ein anderer Fehler.

**Comment by copystring** [comment]
https://github.com/copystring/ioBroker.roborock/issues/491
