### ISSUE TITLE
0.5.3 startet nicht

### ISSUE THREAD

**Issue by krobipd** [copystring/ioBroker.roborock#489]
Hallo leider startet die 0.5.3 bei mir nicht 

hier das log

`
2024-02-01 22:50:15.643 - info: roborock.0 (2253) starting. Version 0.5.3 in /opt/iobroker/node_modules/iobroker.roborock, node: v20.11.0, js-controller: 5.0.19
--
2024-02-01 22:50:15.660 - info: roborock.0 (2253) Starting adapter. This might take a few minutes depending on your setup. Please wait.
2024-02-01 22:50:21.360 - info: roborock.0 (2253) MQTT initialized
2024-02-01 22:50:22.241 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:23.241 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:23.377 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:24.377 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:24.525 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:25.526 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:25.662 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:26.664 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:26.803 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:27.804 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:27.956 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:28.956 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:29.104 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:30.104 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:30.246 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:31.246 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:31.388 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:32.388 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:32.536 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:33.537 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:33.695 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:34.696 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:34.832 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:35.831 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:35.962 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:36.962 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:37.106 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:38.106 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:38.251 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:39.251 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:39.380 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:40.380 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:40.512 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:41.513 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:41.651 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:42.652 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:42.788 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:43.788 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:43.916 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:44.917 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:45.049 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:46.049 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:46.178 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:47.178 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:47.315 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:48.315 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:48.448 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:49.450 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:49.575 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:50.577 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:50.704 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:51.361 - warn: roborock.0 (2253) Restart initiated
2024-02-01 22:50:51.405 - info: roborock.0 (2253) terminating
2024-02-01 22:50:51.406 - info: roborock.0 (2253) Terminated (NO_ERROR): Without reason
2024-02-01 22:50:51.704 - warn: roborock.0 (2253) MQTT connection reconnect.
2024-02-01 22:50:51.837 - warn: roborock.0 (2253) MQTT connection close.
2024-02-01 22:50:51.866 - info: roborock.0 (2253) terminating
2024-02-01 22:50:51.928 - error: roborock.0 (2253) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-02-01 22:50:51.929 - error: roborock.0 (2253) unhandled promise rejection: Connection is closed.
2024-02-01 22:50:51.934 - error: roborock.0 (2253) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:633:26)
at Socket.emit (node:events:518:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2024-02-01 22:50:51.935 - error: roborock.0 (2253) Connection is closed.
2024-02-01 22:50:51.947 - error: roborock.0 (2253) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-02-01 22:50:51.947 - error: roborock.0 (2253) unhandled promise rejection: Connection is closed.
2024-02-01 22:50:51.947 - error: roborock.0 (2253) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:633:26)
at Socket.emit (node:events:518:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2024-02-01 22:50:51.947 - error: roborock.0 (2253) Connection is closed.
2024-02-01 22:50:51.949 - error: roborock.0 (2253) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-02-01 22:50:51.949 - error: roborock.0 (2253) unhandled promise rejection: Connection is closed.
2024-02-01 22:50:51.949 - error: roborock.0 (2253) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:633:26)
at Socket.emit (node:events:518:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2024-02-01 22:50:51.950 - error: roborock.0 (2253) Connection is closed.
2024-02-01 22:50:51.952 - error: roborock.0 (2253) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-02-01 22:50:51.953 - error: roborock.0 (2253) unhandled promise rejection: Connection is closed.
2024-02-01 22:50:51.953 - error: roborock.0 (2253) Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:633:26)
at Socket.emit (node:events:518:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2024-02-01 22:50:51.954 - error: roborock.0 (2253) Connection is closed.
2024-02-01 22:50:51.955 - error: roborock.0 (2253) Failed to get home details: Error: Connection is closed.
at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
at Object.onceWrapper (node:events:633:26)
at Socket.emit (node:events:518:28)
at Socket.emit (node:domain:488:12)
at TCP. (node:net:337:12)
2024-02-01 22:50:52.035 - error: host.krobis-iotctr Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-02-01 22:50:52.036 - error: host.krobis-iotctr Caught by controller[1]: Error: Connection is closed.
2024-02-01 22:50:52.036 - error: host.krobis-iotctr Caught by controller[1]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
2024-02-01 22:50:52.036 - error: host.krobis-iotctr Caught by controller[1]: at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
2024-02-01 22:50:52.036 - error: host.krobis-iotctr Caught by controller[1]: at Object.onceWrapper (node:events:633:26)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[1]: at Socket.emit (node:events:518:28)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[1]: at Socket.emit (node:domain:488:12)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[1]: at TCP. (node:net:337:12)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[2]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[3]: Error: Connection is closed.
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[3]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[3]: at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[3]: at Object.onceWrapper (node:events:633:26)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[3]: at Socket.emit (node:events:518:28)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[3]: at Socket.emit (node:domain:488:12)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[3]: at TCP. (node:net:337:12)
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[4]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[4]: Error: Connection is closed.
2024-02-01 22:50:52.037 - error: host.krobis-iotctr Caught by controller[4]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[4]: at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[4]: at Object.onceWrapper (node:events:633:26)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[4]: at Socket.emit (node:events:518:28)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[4]: at Socket.emit (node:domain:488:12)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[4]: at TCP. (node:net:337:12)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[5]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[5]: Error: Connection is closed.
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[5]: at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[5]: at Socket. (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[5]: at Object.onceWrapper (node:events:633:26)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[5]: at Socket.emit (node:events:518:28)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[5]: at Socket.emit (node:domain:488:12)
2024-02-01 22:50:52.038 - error: host.krobis-iotctr Caught by controller[5]: at TCP. (node:net:337:12)
2024-02-01 22:50:52.039 - info: host.krobis-iotctr instance system.adapter.roborock.0 terminated with code 0 (NO_ERROR)
2024-02-01 22:50:52.039 - info: host.krobis-iotctr Restart adapter system.adapter.roborock.0 because enabled
2024-02-01 22:51:22.091 - info: host.krobis-iotctr instance system.adapter.roborock.0 started with pid 2348

`

**Comment by copystring** [comment]
Hi, stimmt. 0.5.4 kommt gleich. Da ist der Fehler behoben.
