### ISSUE TITLE
S8 Pro Ultra Datenpunkte für u.a. Ultra-Station fehlen

### ISSUE THREAD

**Issue by DonToben** [copystring/ioBroker.roborock#494]
Beim S8 Pro Ultra fehlen unter anderem die Datenpunkte für Mop waschen und Staubbehälter absaugen.

commands.app_start_wash
commands.app_start_collect_dust

Danke für deine Arbeit.

Hier der Debug Log.

[S8 Pro Ultra.txt](https://github.com/copystring/ioBroker.roborock/files/14224015/S8.Pro.Ultra.txt)

![grafik](https://github.com/copystring/ioBroker.roborock/assets/61901880/13d3e6cf-8765-43a4-b13f-10675ee59a39)

**Comment by copystring** [comment]
Hallo @DonToben,

in der neuen dev habe ich ein neues Feature eingebaut. Dadurch ist es möglich, dass unterstützte Parameter/Befehle, etc. automatisch erkannt werden. Dann muss ich nicht jeden neuen Saugroboter komplett neu einbauen. Stattdessen müssen dann nur neue Befehle eingebaut werden, welche dann automatisch dem entsprechenden Saugroboter zugewiesen werden.

Auf dieser Basis habe ich `app_start_wash` und `app_start_collect_dust` eingebaut. Wäre klasse, wenn du das testen und mir eine Rückmeldung geben würdest. Bei mir war der Test erfolgreich.

**Comment by DonToben** [comment]
Mit der Stable kam auch noch folgender Fehler.

`<html><body>

roborock.0 | 2024-02-10 08:44:18.154 | info | terminating
-- | -- | -- | --
roborock.0 | 2024-02-10 08:44:18.146 | error | Cannot read properties of undefined (reading 'code')
roborock.0 | 2024-02-10 08:44:18.146 | error | TypeError:  Cannot read properties of undefined (reading 'code')    at  /opt/iobroker/node_modules/iobroker.roborock/lib/message.js:178:16    at  new Promise (<anonymous>)    at message.resolve102Message  (/opt/iobroker/node_modules/iobroker.roborock/lib/message.js:177:10)     at EventEmitter.listener102  (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:120:49)     at EventEmitter.emit  (/opt/iobroker/node_modules/eventemitter2/lib/eventemitter2.js:1047:22)     at Socket.<anonymous>  (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:79:10)     at Socket.emit (node:events:513:28)    at addChunk  (node:internal/streams/readable:324:12)    at readableAddChunk  (node:internal/streams/readable:297:9)    at Readable.push  (node:internal/streams/readable:234:10)
roborock.0 | 2024-02-10 08:44:18.144 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'code')
roborock.0 | 2024-02-10 08:44:18.144 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().


</body>
</html>`

**Comment by DonToben** [comment]
Hier der Log zur Dev 0.5.4
Die zwei Befehle sind jetzt vorhanden. Danke. 
Gibt es eigentlich einen Befehl zum Mop Trockner ein und ausschalten?

[S8 Pro Ultra 0.5.4.txt](https://github.com/copystring/ioBroker.roborock/files/14228889/S8.Pro.Ultra.0.5.4.txt)

**Comment by copystring** [comment]
Vielleicht. Gibt es dafür einen Befehl in der App?

**Comment by DonToben** [comment]
Ja, zwei sogar. Automatisch und manuell.

![Screenshot_20240210_115724_Roborock](https://github.com/copystring/ioBroker.roborock/assets/61901880/9010504d-e8f9-48d7-8a4b-85f6b5f741a0)
![Screenshot_20240210_115705_Roborock](https://github.com/copystring/ioBroker.roborock/assets/61901880/a42aab7f-3be4-45ae-b1c3-7a5c2b2fe59a)

**Comment by copystring** [comment]
Du meinst das automatische Trocknen?

**Comment by DonToben** [comment]
Beides. Das automatische Trocknen ein und aus. Manuell kann man es auch anstoßen.

**Comment by DonToben** [comment]
> Mit der Stable kam auch noch folgender Fehler.
> 
> `
> roborock.0 	2024-02-10 08:44:18.154 	info 	terminating
> roborock.0 	2024-02-10 08:44:18.146 	error 	Cannot read properties of undefined (reading 'code')
> roborock.0 	2024-02-10 08:44:18.146 	error 	TypeError: Cannot read properties of undefined (reading 'code') at /opt/iobroker/node_modules/iobroker.roborock/lib/message.js:178:16 at new Promise () at message.resolve102Message (/opt/iobroker/node_modules/iobroker.roborock/lib/message.js:177:10) at EventEmitter.listener102 (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:120:49) at EventEmitter.emit (/opt/iobroker/node_modules/eventemitter2/lib/eventemitter2.js:1047:22) at Socket. (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:79:10) at Socket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:324:12) at readableAddChunk (node:internal/streams/readable:297:9) at Readable.push (node:internal/streams/readable:234:10)
> roborock.0 	2024-02-10 08:44:18.144 	error 	unhandled promise rejection: Cannot read properties of undefined (reading 'code')
> roborock.0 	2024-02-10 08:44:18.144 	error 	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
> `

Diese Fehlermeldung kommt auch noch mit der DEV.

**Comment by DonToben** [comment]
@copystring 
Mit der 0.4.4 kein Adapter Neustart nach jedem Befehl. 
Aktuell muss ich diese verwenden, damit der S8 Pro Ultra läuft. Die Ultra Station Befehle fehlen natürlich.

**Comment by copystring** [comment]
> > Mit der Stable kam auch noch folgender Fehler.
> > `roborock.0 	2024-02-10 08:44:18.154 	info 	terminating roborock.0 	2024-02-10 08:44:18.146 	error 	Cannot read properties of undefined (reading 'code') roborock.0 	2024-02-10 08:44:18.146 	error 	TypeError: Cannot read properties of undefined (reading 'code') at /opt/iobroker/node_modules/iobroker.roborock/lib/message.js:178:16 at new Promise () at message.resolve102Message (/opt/iobroker/node_modules/iobroker.roborock/lib/message.js:177:10) at EventEmitter.listener102 (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:120:49) at EventEmitter.emit (/opt/iobroker/node_modules/eventemitter2/lib/eventemitter2.js:1047:22) at Socket. (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:79:10) at Socket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:324:12) at readableAddChunk (node:internal/streams/readable:297:9) at Readable.push (node:internal/streams/readable:234:10) roborock.0 	2024-02-10 08:44:18.144 	error 	unhandled promise rejection: Cannot read properties of undefined (reading 'code') roborock.0 	2024-02-10 08:44:18.144 	error 	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`
> 
> @copystring Diese Fehlermeldung kommt auch noch mit der DEV.

Der Fehler ist in der neuesten dev behoben. Für alles andere muss ich erstmal Zeit finden.

**Comment by DonToben** [comment]
@copystring 
Vielen Dank.
Anbei das aktuelle Log. Der Reset ist weg.
Dryer command ist vorhanden, aber funktioniert noch nicht.

[DEV_0.5.4.txt](https://github.com/copystring/ioBroker.roborock/files/14321951/DEV_0.5.4.txt)

**Comment by copystring** [comment]
> Dryer command ist vorhanden, aber funktioniert noch nicht.

Wie meinst du das? Ich habe diesbezüglich nichts angepasst.

**Comment by DonToben** [comment]
Dachte, das command app_set_dryer_status war vorher nicht da.
Siehe Bild. 

![Screenshot_20240218_170840_Opera](https://github.com/copystring/ioBroker.roborock/assets/61901880/2e0f1709-31b0-47f9-9fce-7a0a98a2b7f8)

**Comment by copystring** [comment]
OK. Dann war das schon vorher drin. Habe das nicht überprüft.
Um den Befehl zum Trocknen einzubauen, müsstest du den Saugroboter mit mir über die App teilen. Mein Account ist copystring@gmail.com. Dann würde ich den Befehl zum Trocknen einmal auslösen und mitschneiden. Danach könntest du das Teilen wieder beenden.

**Comment by DonToben** [comment]
@copystring 
Habe den Account geteilt.

**Comment by copystring** [comment]
OK. Ist eingebaut. Teste mal die neue dev.

**Comment by DonToben** [comment]
Das automatische Trocknen (aktivieren und die Zeit einstellen) funktioniert. Den Befehl für das manuelle Trocknen, in der App über Andocken und Trocknen, finde ich noch nicht.

**Comment by copystring** [comment]
Hast du kein `app_set_dryer_setting`?

**Comment by DonToben** [comment]
Doch, das funktioniert auch. Hier kann man das automatische Trocknen einstellen. Stelle ich einen Wert ein, dann trocknet er **nach dem nächsten Wischen.**

Es gibt aber noch einen weiteren App Button. Hier wird unabhängig ob automatisches Trocknen aktiviert, das Trocknen gestartet. Sprich, Button drücken und er trocknet sofort.

**Comment by copystring** [comment]
Ich habe den Datenverkehr mitgeschnitten. Die App startet über `app_set_dryer_status` das Trocknen und über `app_set_dryer_setting` kann eingestellt werden, wie lange getrocknet werden soll. Beides ist im Adapter eingebaut.

**Comment by DonToben** [comment]
App_set_dryer_status ist vorhanden, der Trockner startet aber nicht, wenn ich den state auf on setze. Über die App funktioniert es. 
VG

**Comment by copystring** [comment]
Was steht im Protokoll?

**Comment by DonToben** [comment]
Sorry, sitz nicht mehr vorm PC. Daher übers Smartphone.

-18 20:57:01.071 - debug: roborock.0 (23013) onStateChange: app_set_dryer_status with value: {"status": 1}
2024-02-18 20:57:01.095 - debug: roborock.0 (23013) Length of message queue: 0
2024-02-18 20:57:01.096 - debug: roborock.0 (23013) Command: app_set_dryer_status result: undefined
2024-02-18 20:57:01.233 - debug: roborock.0 (23013) dps debug: {"id":633,"result":{"water_box_mode":202}}
2024-02-18 20:57:01.594 - debug: roborock.0 (23013) dps debug: {"id":1276,"result":[{"msg_ver":2,"msg_seq":4261,"state":8,"battery":100,"clean_time":1522,"clean_area":24152500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":3,"water_box_status":1,"fan_power":102,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":202,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":385,"is_exploring":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":7,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":10,"mop_mode":300,"back_type":-1,"wash_phase":0,"wash_ready":0,"wash_status":512,"debug_mode":0,"collision_avoid_status":1,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0,"dry_status":0,"rdt":0,"clean_percent":0,"rss":2,"dss":2729,"common_status":2,"events":[],"switch_status":0,"last_clean_t":1708275373}]}
2024-02-18 20:57:03.540 - debug: roborock.0 (23013) dps debug: {"id":1277,"result":[{"msg_ver":2,"msg_seq":4262,"state":8,"battery":100,"clean_time":1522,"clean_area":24152500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":3,"water_box_status":1,"fan_power":102,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":202,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":385,"is_exploring":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":7,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":10,"mop_mode":300,"back_type":-1,"wash_phase":0,"wash_ready":0,"wash_status":512,"debug_mode":0,"collision_avoid_status":1,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0,"dry_status":0,"rdt":0,"clean_percent":0,"rss":2,"dss":2729,"common_status":2,"events":[],"switch_status":0,"last_clean_t":1708275373}]}
2024-02-18 20:57:03.951 - debug: roborock.0 (23013) dps debug: {"id":1278,"result":["ok"]}
2024-02-18 20:57:05.329 - debug: roborock.0 (23013) dps debug: {"id":1279,"result":[{"msg_ver":2,"msg_seq":4263,"state":8,"battery":100,"clean_time":1522,"clean_area":24152500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":3,"water_box_status":1,"fan_power":102,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":202,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":385,"is_exploring":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":7,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":10,"mop_mode":300,"back_type":-1,"wash_phase":0,"wash_ready":0,"wash_status":512,"debug_mode":0,"collision_avoid_status":1,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0,"dry_status":0,"rdt":0,"clean_percent":0,"rss":2,"dss":2729,"common_status":2,"events":[],"switch_status":0,"last_clean_t":1708275373}]}
2024-02-18 20:57:07.223 - debug: roborock.0 (23013) dps debug: {"id":1281,"result":[{"msg_ver":2,"msg_seq":4264,"state":8,"battery":100,"clean_time":1522,"clean_area":24152500,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":3,"water_box_status":1,"fan_power":102,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"water_box_mode":202,"water_box_carriage_status":1,"mop_forbidden_enable":1,"camera_status":385,"is_exploring":0,"adbumper_status":[0,0,0],"water_shortage_status":0,"dock_type":7,"dust_collection_status":0,"auto_dust_collection":1,"avoid_count":10,"mop_mode":300,"back_type":-1,"wash_phase":0,"wash_ready":0,"wash_status":512,"debug_mode":0,"collision_avoid_status":1,"switch_map_mode":0,"dock_error_status":0,"charge_status":1,"unsave_map_reason":0,"unsave_map_flag":0,"dry_status":0,"rdt":0,"clean_percent":0,"rss":2,"dss":2729,"common_status":2,"events":[],"switch_status":0,"last_clean_t":1708275373}]}
2024-02-18 20:57:07.391 - debug: roborock.0 (23013) onStateChange: app_set_dryer_status with value: {"status": 0}
2024-02-18 20:57:07.394 - debug: roborock.0 (23013) dps debug: {"id":1280,"result":["ok"]}
2024-02-18 20:57:07.414 - debug: roborock.0 (23013) Length of message queue: 0
2024-02-18 20:57:07.415 - debug: roborock.0 (23013) Command: app_set_dryer_status result: undefined

**Comment by copystring** [comment]
Der Befehl wird anscheinend sauber quittiert:

```
2024-02-18 20:57:07.391 - debug: roborock.0 (23013) onStateChange: app_set_dryer_status with value: {"status": 0}
2024-02-18 20:57:07.394 - debug: roborock.0 (23013) dps debug: {"id":1280,"result":["ok"]}
```

Sicher, dass es nicht läuft?

**Comment by copystring** [comment]
Teste bitte mal die neue dev

**Comment by DonToben** [comment]
Funktioniert auch nicht mit der neuesten Dev.
Btw. Wenn ich es über die App manuell anstoße, dann nimmt er die Trocknungszeit her, welche zuvor im Einstellungsmenü festgelegt wurde. 2h, 3h, oder 4h. Auch wenn automatisches Trocknen deaktiviert ist.
Evtl musst du ja noch einen Parameter zusätzlich mitsenden für die Zeit. Nur eine Idee von jemandem, welcher vom Programmieren wenig Ahnung hat.

**Comment by copystring** [comment]
OK. Habe den Fehler gefunden und behoben. Mein Test mit deinem und meinen Saugroboter lief erfolgreich durch. Habe den Fix in die neue dev hochgeladen.

**Comment by copystring** [comment]
Interessant ist, dass dieser Befehl über die App für den S7 MaxV gar nicht ausgelöst werden kann. Wohl aber über meinen Adapter. Das geht aber erst jetzt, nachdem ich mitschneiden konnte, wie die App das für deinen Saugroboter macht ;)

**Comment by DonToben** [comment]
Perfekt. Funktioniert jetzt. 
Vielen Dank.

**Comment by copystring** [comment]
Gern.
