### ISSUE TITLE
Buttons on the webpage don't refresh to the matching state of a robot. 

### ISSUE THREAD

**Issue by manny4566** [copystring/ioBroker.roborock#537]
Describe the bug
The Buttons of the webpage don't shows the current status of a selected robot.

    Go to 'http://ip:6824/map.html'
    Click on "Start" button for the first robot -> the robot starts  -> The button changed to "pause".
    Select a other robot.
    It is not possible to start the robot, because the "pause" button stay active. 
    A refresh of the page is necessary for refreshing the buttons so that you can click on "start" again for the second one. 

Expected behavior
The button status need to be refreshed to a matching status of the robot after changing the robot in the drop down list or refreshing the page. ( The robot state need do be read out and processed.)

Other example.
After refreshing the page, the buttons changed to "start". Also if the robot already works. So it is not possible to send a "pause".
The reverse case. :)

Thank you

Screenshots & Logfiles
![grafik](https://github.com/copystring/ioBroker.roborock/assets/23473485/064f3686-f054-4453-aa53-2e9ea090bf60)

Versions:

    Adapter version: 0.6.2
    JS-Controller version: 5.0.19
    Node version: v18.19.0
    Operating system: Debian 12

**Comment by manny4566** [comment]
> Please try the new dev here: https://github.com/copystring/ioBroker.roborock/tree/dev in my testing it worked perfectly. However, this chance required to request that robot state every second. Hopefully this will not cause any long term problems.

Hi,

I have still problems. Hmmm, i think there are still bugs. 

<html><body>
roborock.0 | 2024-05-21 14:09:39.629 | error | Failed to launch go2rtc: Error: spawn ETXTBSY
-- | -- | -- | --
roborock.0 | 2024-05-21 14:09:38.316 | info | Starting adapter finished. Lets go!!!!!!!
roborock.0 | 2024-05-21 14:08:55.834 | info | MQTT initialized
roborock.0 | 2024-05-21 14:08:55.365 | info | Starting adapter. This might take a few minutes depending on your setup. Please wait.
roborock.0 | 2024-05-21 14:08:55.359 | info | starting.  Version 0.6.4 (non-npm: copystring/ioBroker.roborock#dev) in  /opt/iobroker/node_modules/iobroker.roborock, node: v18.20.2,  js-controller: 5.0.19
roborock.0 | 2024-05-21 14:08:55.282 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
roborock.0 | 2024-05-21 14:08:51.713 | error | Failed  to get home details: Error: Connection is closed.    at  Redis.sendCommand  (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24)    at  Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25)     at ObjectsInRedisClient._setObject  (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:2727:45)     at Immediate.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:2918:44)     at process.processImmediate (node:internal/timers:478:21)
roborock.0 | 2024-05-21 14:08:51.712 | error | Connection is closed.
roborock.0 | 2024-05-21 14:08:51.712 | error | Error:  Connection is closed.    at Redis.sendCommand  (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24)    at  Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25)     at ObjectsInRedisClient._setObject  (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:2727:45)     at Immediate.<anonymous>  (/opt/iobroker/node_modules/@iobroker/db-objects-redis/build/lib/objects/objectsInRedisClient.js:2918:44)     at process.processImmediate (node:internal/timers:478:21)
roborock.0 | 2024-05-21 14:08:51.712 | error | unhandled promise rejection: Connection is closed.
roborock.0 | 2024-05-21 14:08:51.711 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
roborock.0 | 2024-05-21 14:08:51.709 | info | terminating
roborock.0 | 2024-05-21 14:08:51.209 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
roborock.0 | 2024-05-21 14:08:51.209 | info | terminating
roborock.0 | 2024-05-21 14:08:51.207 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>
