### ISSUE TITLE
Fehlermeldung: Failed to execute get_status on robot xxx ...

### ISSUE THREAD

**Issue by Norb1204** [copystring/ioBroker.roborock#549]
Hallo,
nach update PI von Debian 10 nach 12 kommt kurz nach dem Start des Adapters ca. jede Sekunde eine Fehlermeldung.
Adapterversion: Aktuelle DEV (18.05.2024)

Als Anhang das LOG:
[log.txt](https://github.com/copystring/ioBroker.roborock/files/15369026/log.txt)

**Comment by copystring** [comment]
Ja, ich habe dafür einen fix vorbereitet, aber noch nicht hochgeladen.

**Comment by copystring** [comment]
Testest du bitte die neue dev? Da sollte es jetzt wieder laufen.

**Comment by Norb1204** [comment]
Fehlermeldungen sind zwar weg aber der DeviceStatus, CleaningInfo wird nicht mehr aktualisiert.

<img width="599" alt="image" src="https://github.com/copystring/ioBroker.roborock/assets/132662785/617ae862-bc89-439d-a9a6-ebb89e5a11f3">

<img width="602" alt="image" src="https://github.com/copystring/ioBroker.roborock/assets/132662785/80d3cf4a-1ce4-48cf-99f0-346b800dc738">

**Comment by copystring** [comment]
Bist du dir sicher, dass das nie aktualisiert wird? Ich kann das bei mir nicht reproduzieren. Vielleicht hast du aber noch nicht die neueste dev installiert?

**Comment by Norb1204** [comment]
Habe mal den Adapter gelöscht und neu installiert.
Bei der Standard-Installation funktioniert die Aktualisierung. Dann die DEV installiert, hier funktioniert die Aktualisierung nicht.
Habe z.Z. zwei ioBroker am laufen. Einen mit Debian 10 der andere mit 12. Bei beiden das gleiche Phänomen.

**Comment by copystring** [comment]
Merkwürdig, aber OK. Muss ich mir angucken. Gibt es im Log neue Fehler?

**Comment by Norb1204** [comment]
Bei der Standard-Installation kommen halt noch die altbekannten Fehlermeldungen.
Ich werde morgen mir das ganze genauer anschauen und Rückmeldung geben.
Momentan habe ich die Vorgängerversion der DEV am laufen.

**Comment by Norb1204** [comment]
Als Anhang ein LOG von mehreren Minuten.
Mit der letzten DEV werden DeviceStatus und CleaningInfo nicht mehr aktualisiert, auch beim Neustart des Adapters nicht.
Erst wenn ich den Adapter lösche und neu installiere funktioniert die Aktualisierung wieder.

[log.txt](https://github.com/copystring/ioBroker.roborock/files/15385048/log.txt)

**Comment by nicomania** [comment]
Habe ich auch schon seit Längerem. Kommt jedes Mal, wenn ich eine Reinigung (über die App) starte.

Roborock S8
Adapter v0.6.4
Node.js v18.19.0
NPM 10.5.1

```
roborock.0 | 2024-05-21 08:21:50.387 | error | Failed to execute get_status on robot 6FkwKSEbh3Tm0119AtENqL TypeError: this.adapter.getMap is not a function at vacuum.getParameter (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:279:31) at Roborock.updateDataMinimumData (/opt/iobroker/node_modules/iobroker.roborock/main.js:671:4)
-- | -- | -- | --
roborock.0 | 2024-05-21 07:23:57.525 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:32:25.042 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:32:07.604 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:31:34.976 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:29:11.213 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:26:47.228 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:20:47.108 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:17:47.053 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:14:08.623 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:11:47.374 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-05-21 06:08:47.030 | error | Failed to execute get_map_v1 on robot 6FkwKSEbh3Tm0119AtENqL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Norb1204** [comment]
Geht noch nicht 100%, teilweise werden die Datenpunkte jede Sekunde aktualisiert. Es gibt auch noch ein paar Fehlermeldungen (siehe LOG).

[log.txt](https://github.com/copystring/ioBroker.roborock/files/15404712/log.txt)

**Comment by copystring** [comment]
Das Aktualisieren jede Sekunde ist ab sofort erstmal so gewollt.
Zum Absturz: war das eine einmalige Sache oder kommt das ständig? Solche Abstürze sind besonders schwer zu finden.

**Comment by nicomania** [comment]
danke auch von mir. @copystring kannst du das bitte ins beta repo schieben? dann teste ich auch mal.

**Comment by copystring** [comment]
> danke auch von mir. @copystring kannst du das bitte ins beta repo schieben? dann teste ich auch mal.

Ja, sobald ich die letzten Fehler in der dev-Version behoben habe, werde ich eine neue beta in latest bereitstellen. Die letzten Monate fehlt mir einiges an Zeit. Deshalb ist es etwas ruhiger geworden.

**Comment by c-hum** [comment]
Running on the current dev version.
```roborock.0
2024-08-11 11:09:05.874	error	Failed to execute get_map_v1 on robot ABC TypeError: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array at _write (node:internal/streams/writable:480:13) at Gzip.Writable.end (node:internal/streams/writable:821:17) at zlibBuffer (node:zlib:130:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:819:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:69:11) at processTicksAndRejections (node:internal/process/task_queues:95:5)```

**Comment by freakyfreaky** [comment]
Habe auch den Fehler. Adapter 0.6.16 heute neu installiert da Sauger in Betrieb genommen
Failed to execute get_map_v1 on robot 7Q17LTIuWAbBMQlX2Vbleq (unknown model): Error: Failed to convert JavaScript value `Undefined` into rust type `String` at /opt/iobroker/node_modules/iobroker.roborock/lib/mapCreator.js:654:29 at Array.forEach (<anonymous>) at MapCreator.canvasMap (/opt/iobroker/node_modules/iobroker.roborock/lib/mapCreator.js:631:30) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:84:46) at Roborock.initializeDeviceUpdates (/opt/iobroker/node_modules/iobroker.roborock/main.js:334:4)
