### ISSUE TITLE
Reinigungsprozess kann nicht gestartet werden

### ISSUE THREAD

**Issue by StefanD17** [copystring/ioBroker.roborock#599]
Befehle, Beispielsweise Zonenreinigung werden nicht ausgeführt. 

Errorlog:
	
Zeit
debug
Nachricht

roborock.1
2024-08-18 09:56:40.893	info	Starting adapter finished. Lets go!!!!!!!

roborock.1
2024-08-18 09:55:57.205	info	MQTT initialized

roborock.1
2024-08-18 09:55:56.167	info	Starting adapter. This might take a few minutes depending on your setup. Please wait.

roborock.1
2024-08-18 09:55:56.133	info	starting. Version 0.6.6 in /opt/iobroker/node_modules/iobroker.roborock, node: v20.16.0, js-controller: 6.0.10

roborock.1
2024-08-18 09:55:07.836	warn	redis get roborock.1.HomeData, error - Connection is closed.

roborock.1
2024-08-18 09:55:07.835	warn	redis get roborock.1.HomeData, error - Connection is closed.

roborock.1
2024-08-18 09:55:07.748	info	terminating

roborock.1
2024-08-18 09:55:07.194	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

roborock.1
2024-08-18 09:55:07.193	info	terminating

roborock.1
2024-08-18 09:55:07.153	error	Unexpected non-whitespace character after JSON at position 5

roborock.1
2024-08-18 09:55:07.152	error	SyntaxError: Unexpected non-whitespace character after JSON at position 5 at JSON.parse (<anonymous>) at Roborock.onStateChange (/opt/iobroker/node_modules/iobroker.roborock/main.js:1376:56) at Roborock.emit (node:events:519:28) at Roborock.emit (node:domain:488:12) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11016:53) at processImmediate (node:internal/timers:483:21)

roborock.1
2024-08-18 09:55:06.943	error	unhandled promise rejection: Unexpected non-whitespace character after JSON at position 5

roborock.1
2024-08-18 09:55:06.939	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Versions:**  
 - Adapter version: 0.6.6
 - JS-Controller version: 6.0.10
 - Node version: v20.16.0
 - Operating system: Unraid
 -

**Comment by mickemup** [comment]
Same Here 
With a S6 Pure
Segment clean wird nicht ausgelöst:
roborock.0.Devices.6RqafIo52RYxcUqKpUqoKU.commands.app_segment_clean

![image](https://github.com/user-attachments/assets/c12d559c-1648-4e98-b09c-a490b1863c82)


v0.6.6
JS-Controller version: 6.0.9
Node version: v20.16.0

With the S5 Pure the System is working

**Comment by copystring** [comment]
Ist das mit der dev von GitHub auch so? Die ist hier zu finden: https://github.com/copystring/ioBroker.roborock/tree/dev
Die bitte mal installieren und neu testen. Danke!

**Comment by mickemup** [comment]
Salü

Gerade die Dev installiert

Nun kommt die Meldung bei beiden Saugern...

[image: image.png]

Am So., 18. Aug. 2024 um 18:07 Uhr schrieb copystring <
***@***.***>:

**Comment by copystring** [comment]
@mickemup du hast ein ganz anderes Problem als @StefanD17. Öffne dafür bitte ein neues issue und hänge dafür ein debuglog vom Start des Adapters und die ersten 2 Minuten danach an. Danke.

**Comment by StefanD17** [comment]
@copystring habe gerade die dev version installiert. Leider nach wie vor der selbe Fehler. 


roborock.1
2024-08-18 19:55:23.779	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

roborock.1
2024-08-18 19:55:23.777	info	terminating

roborock.1
2024-08-18 19:55:23.741	error	Unexpected non-whitespace character after JSON at position 5

roborock.1
2024-08-18 19:55:23.741	error	SyntaxError: Unexpected non-whitespace character after JSON at position 5 at JSON.parse (<anonymous>) at Roborock.onStateChange (/opt/iobroker/node_modules/iobroker.roborock/main.js:1398:56) at Roborock.emit (node:events:519:28) at Roborock.emit (node:domain:488:12) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11016:53) at processImmediate (node:internal/timers:483:21)

roborock.1
2024-08-18 19:55:23.541	error	unhandled promise rejection: Unexpected non-whitespace character after JSON at position 5

roborock.1
2024-08-18 19:55:23.537	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

roborock.1
2024-08-18 19:53:49.438	warn	MQTT connection reconnect.

roborock.1
2024-08-18 19:53:49.435	warn	MQTT connection close.

roborock.1
2024-08-18 19:53:49.397	warn	Reconnecting mqtt client!

roborock.1
2024-08-18 18:54:42.181	info	Starting adapter finished. Lets go!!!!!!!

roborock.1
2024-08-18 18:53:49.394	info	MQTT initialized

roborock.1
2024-08-18 18:53:48.325	info	Starting adapter. This might take a few minutes depending on your setup. Please wait.

roborock.1
2024-08-18 18:53:48.284	info	starting. Version 0.6.6 (non-npm: copystring/ioBroker.roborock#dev) in /opt/iobroker/node_modules/iobroker.roborock, node: v20.16.0, js-controller: 6.0.10

**Comment by copystring** [comment]
Taucht der Fehler auf, wenn du `app_goto_target` ausführst? Wenn ja, welchen Wert übergibst du an `app_goto_target`? Den Wert bitte hier eins zu eins hier hereinschreiben.

**Comment by StefanD17** [comment]
Ich hatte bis dato immer `app_zoned_clean` verwendet. Testweise nun auch `app_goto_target`. Übergeben wurde dieser wert:
26100,29950,29550,33750,1

**Comment by copystring** [comment]
OK. Da liegt der Fehler.
`app_zoned_clean` erwartet dieses Format: `[26100,29950,29550,33750,1]`
`app_goto_target` kann nur so gesteuert werden: `[26100,29950]`

Ich habe den Code in der neuen dev so angepasst, dass dies nun validiert wird. Bei Fehlern wird eine entsprechende Meldung ins Log ausgegeben. Würdest du das bitte für mich testen?
