### ISSUE TITLE
[BUG] Fehler bei der Kommunikation

### ISSUE THREAD

**Issue by A1uca2d** [copystring/ioBroker.roborock#696]
### Bug Description

Die genauen Auswirkungen kenne ich noch nicht. 
Aber seit gestern kommt es immer mal wieder dazu, dass der Adapter einen Fehler (gelb) anzeigt. 

### Steps to Reproduce

Ich habe nichts gemacht. Es gibt für mich keinen genauen Auslöser.

### Expected Behavior

-

### Debug Log

roborock.0 | 2024-11-03 11:34:53.686 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
roborock.0 | 2024-11-03 11:34:53.685 | error | Exception-Code: EAI_AGAIN: getaddrinfo EAI_AGAIN euiot.roborock.com
roborock.0 | 2024-11-03 11:34:53.685 | error | Error: getaddrinfo EAI_AGAIN euiot.roborock.com at AxiosError.from (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/dist/node/axios.cjs:876:14) at RedirectableRequest.handleRequestError (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/dist/node/axios.cjs:3156:25) at RedirectableRequest.emit (node:events:519:28) at eventHandlers.<computed> (/opt/iobroker/node_modules/follow-redirects/index.js:38:24) at ClientRequest.emit (node:events:519:28) at emitErrorEvent (node:_http_client:101:11) at TLSSocket.socketErrorListener (node:_http_client:504:5) at TLSSocket.emit (node:events:519:28) at emitErrorNT (node:internal/streams/destroy:169:8) at emitErrorCloseNT (node:internal/streams/destroy:128:3) at Axios.request (/opt/iobroker/node_modules/iobroker.roborock/node_modules/axios/dist/node/axios.cjs:4287:41) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async Roborock.getUserData (/opt/iobroker/node_modules/iobroker.roborock/main.js:225:21) at async Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:85:20)
roborock.0 | 2024-11-03 11:34:53.685 | error | unhandled promise rejection: getaddrinfo EAI_AGAIN euiot.roborock.com
roborock.0 | 2024-11-03 11:34:53.685 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
roborock.0 | 2024-11-03 11:34:53.679 | error | Error in getUserData: getaddrinfo EAI_AGAIN euiot.roborock.com
roborock.0 | 2024-11-03 11:34:06.749 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
roborock.0 | 2024-11-03 11:34:06.748 | error | Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-11-03 11:34:06.748 | error | TypeError: Cannot read properties of undefined (reading 'captureException') at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:1234:44) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:132:17) at MqttClient.emit (node:events:519:28) at MqttClient._setupReconnect (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/build/lib/client.js:799:22) at MqttClient._cleanUp (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/build/lib/client.js:848:18) at MqttClient.onKeepaliveTimeout (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/build/lib/client.js:1051:14) at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/build/lib/KeepaliveManager.js:67:29) at listOnTimeout (node:internal/timers:581:17) at process.processTimers (node:internal/timers:519:7)
roborock.0 | 2024-11-03 11:34:06.748 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-11-03 11:34:06.748 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
roborock.0 | 2024-11-03 11:34:06.748 | error | Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-11-03 11:34:06.748 | error | TypeError: Cannot read properties of undefined (reading 'captureException') at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:1234:44) at MqttClient.<anonymous> (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:106:17) at MqttClient.emit (node:events:531:35) at MqttClient.onKeepaliveTimeout (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/build/lib/client.js:1049:14) at Timeout.<anonymous> (/opt/iobroker/node_modules/iobroker.roborock/node_modules/mqtt/build/lib/KeepaliveManager.js:67:29) at listOnTimeout (node:internal/timers:581:17) at process.processTimers (node:internal/timers:519:7)
roborock.0 | 2024-11-03 11:34:06.747 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-11-03 11:34:06.747 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
roborock.0 | 2024-11-03 11:34:06.746 | error | Failed to execute client.on("offline") on robot undefined (unknown model): MQTT connection offline: undefined
roborock.0 | 2024-11-03 11:34:06.744 | error | Failed to execute client.on("error") on robot undefined (unknown model): MQTT connection error: Error: Keepalive timeout

### Adapter Version

0.6.17

### JS-Controller Version

6.0.11

### Node.js Version

20.18.0

### Operating System

Ubuntu

**Comment by sjfm-design** [comment]
ic denke, da bin ich auch dabei.
`<html>
<body>

host.ioBroker | 2024-11-03 13:20:27.902 | warn | Do not restart adapter system.adapter.roborock.0 because restart loop detected
-- | -- | -- | --
host.ioBroker | 2024-11-03 13:20:27.902 | error | instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.ioBroker | 2024-11-03 13:20:27.902 | error | Caught by controller[0]: at Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:102:20)
host.ioBroker | 2024-11-03 13:20:27.902 | error | Caught by controller[0]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.ioBroker | 2024-11-03 13:20:27.902 | error | Caught by controller[0]: at Roborock.getUserData (/opt/iobroker/node_modules/iobroker.roborock/main.js:253:11)
host.ioBroker | 2024-11-03 13:20:27.902 | error | Caught by controller[0]: Error: Login returned empty userdata.
host.ioBroker | 2024-11-03 13:20:27.902 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
roborock.0 | 2024-11-03 13:20:27.250 | error | Login returned empty userdata.
roborock.0 | 2024-11-03 13:20:27.250 | error | Error: Login returned empty userdata. at Roborock.getUserData (/opt/iobroker/node_modules/iobroker.roborock/main.js:253:11) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:102:20)
roborock.0 | 2024-11-03 13:20:27.248 | error | unhandled promise rejection: Login returned empty userdata.
roborock.0 | 2024-11-03 13:20:27.248 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
roborock.0 | 2024-11-03 13:20:27.051 | error | Error in getUserData: Login returned empty userdata.


</body>
</html>`

schon ein down auf 0.6.15 versucht. 
![grafik](https://github.com/user-attachments/assets/29fa149d-f5a2-4d53-8c07-9baf023130e2)

**Comment by cmdrtom** [comment]
Kann ich ebenfalls bestätigen - bei mir gleiche Fehler.

**Comment by Sandweier** [comment]
War bei mir auch so 0.6.17.Plötzlich undefinierte Fehlerschauer. Habe ich mich direkt über die Mobile App in den  Roborock eigewählt.
Da wurde sofort nach Aufruf  eine weitere Datenschutzrichtlinie signiert verlangt .
Das habe ich gemacht. Siehe da, keine weiteren Fehler mehr. Alles wie vorher und gut.
Vielleicht hilfts.HG aus dem Schwarzwald

**Comment by sjfm-design** [comment]
hmm, hab mich auch gerade über die app angemeldet. nach einer richtlinie wurde ich nicht gefragt.
adapter neustart, alles grün.
strange...

**Comment by copystring** [comment]
Scheint ja gelöst zu sein. Wenn es mit dem kommenden Release 0.6.18 nochmal auftauchen sollte, dann gerne nochmal melden.
