### ISSUE TITLE
[BUG] Fehlermeldungen bei aktivierter Karte S8MaxV Pro

### ISSUE THREAD

**Issue by Matzebhv** [copystring/ioBroker.roborock#720]
### Bug Description

Der Adapter wirft bei aktivierter Karte Fehler im Log. Der Fehler ist erst mit dem Wechsel S6MaxV auf S8MaxV Pro aufgetaucht.
Eine Karte wird nicht erstellt.
`Failed to execute get_map_v1 on robot xxxxxxxxxxT0dDsc9ju (roborock.vacuum.a97): Error: Failed to convert JavaScript value `Undefined` into rust type `String` at /opt/iobroker/node_modules/iobroker.roborock/lib/mapCreator.js:647:29 at Array.forEach (<anonymous>) at MapCreator.canvasMap (/opt/iobroker/node_modules/iobroker.roborock/lib/mapCreator.js:624:30) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:84:46)`

### Steps to Reproduce

Kartenerstellung aktivieren

### Expected Behavior

Kartenerstellung funktioniert ohne Fehler im Log

### Debug Log

Failed to execute get_map_v1 on robot xxxxxxxxxxT0dDsc9ju (roborock.vacuum.a97): Error: Failed to convert JavaScript value `Undefined` into rust type `String` at /opt/iobroker/node_modules/iobroker.roborock/lib/mapCreator.js:647:29 at Array.forEach (<anonymous>) at MapCreator.canvasMap (/opt/iobroker/node_modules/iobroker.roborock/lib/mapCreator.js:624:30) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:84:46)

### Adapter Version

0.6.17

### JS-Controller Version

 7.0.3

### Node.js Version

20.17.0

### Operating System

Debian Bookworm

**Comment by Matzebhv** [comment]
Ich muss meine Meldung revidieren. Ich habe jetzt grade nochmal die Map aktiviert, jetzt ist der Fehler weg. Seltsam. Eventuell waren am Anfang noch nicht alle Daten in der Cloud verfügbar.
