### ISSUE TITLE
[BUG] Qrevo Slim MQTT connection error

### ISSUE THREAD

**Issue by darktwo2** [copystring/ioBroker.roborock#733]
### Bug Description

Ca 12 Stunden nach Adapterstart erscheinen weitere Fehlermeldungen

### Steps to Reproduce

Nach jedem Adapterstart 

### Expected Behavior

keine Meldung

### Debug Log

[roborock.log](https://github.com/user-attachments/files/18127888/roborock.log)

### Adapter Version

0.6.18

### JS-Controller Version

6.0.11

### Node.js Version

20.18.1

### Operating System

docker-container

### Additional Context

Wenn ich die Instanz alle 11 Stunden neu starten lasse gibt es keine Fehler, ist aber keine schöne Lösung. 
Mein zweiter Roborock (Qrevo Master)  hat die Fehler nicht.

**Comment by copystring** [comment]
Hi,

bitte ein Debuglog anhängen.

**Comment by darktwo2** [comment]
Habe im Moment nur das oben Angehängte. Ein weiteres kann ich erst in 12 Stunden erstellen, habe den Adapter gerade neu gestartet.

**Comment by copystring** [comment]
Das hat erstmal nichts mit dem Qrevo Slim zu tun. Es ist ein allgemeiner Fehler mit der Verbindung zum MQTT Server von Roborock. Ging das irgendwann mal?

**Comment by darktwo2** [comment]
Im Moment schient es zu laufen. Ich bekommen die Meldungen aktuell nicht mehr.

**Comment by KallAdam** [comment]
Hi, die letzte Fehlermeldung kann ich aktuell auch bestätigen. 

roborock.0 | 2024-12-18 19:42:44.829 | error | 

Failed to get home details: Error: Not running at healthCheck (node:dgram:922:11) at Socket.bind (node:dgram:242:3) at /opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:213:11 at new Promise (<anonymous>) at localConnector.getLocalDevices (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:185:10) at Roborock.initializeHomeDetails (/opt/iobroker/node_modules/iobroker.roborock/main.js:197:56) at /opt/iobroker/node_modules/iobroker.roborock/main.js:77:4


Bezüglich des ursprünglich eingereichten Fehlers hatte ich auch vor 5 Tagen  jede Sekunde eine Fehlermeldung zur MQTT Verbindung. Nach Adapter Neustart ist dies aber bis heute nicht mehr aufgetaucht.

**Comment by darktwo2** [comment]
seit heute sind bei mir die MQTT Meldungen wieder da

**Comment by KallAdam** [comment]
[iobroker.current.txt](https://github.com/user-attachments/files/18223446/iobroker.current.txt)

aktuell wird wieder der Log mit Fehlermeldungen gespammt. 
Aktuell bin ich bei 24 mb

**Comment by copystring** [comment]
Würdet ihr mal die dev testen? https://github.com/copystring/ioBroker.roborock/tree/dev Fehler bezüglich `Failed to get home details: Error: Not running at healthCheck (node:dgram:922:11) at Socket.bind` ist da eventuell behoben. Am besten mal so 4–5 Tage laufen lassen. Der Fehler kommt leider erst nach langen betrieb.

**Comment by KallAdam** [comment]
Die alten Fehlermeldungen zu MQTT kommen bei mir nicht mehr. Schein zu funktionieren. 

Mit der dev-Version kommen allerdings diverse neue Meldungen: z.B.  
2025-01-03 00:01:30.357  - [33mwarn[39m: roborock.0 (783) Failed to execute get_status on robot 1uowxjxEymn5jp3WAMRw6u (roborock.vacuum.a70): Error: Cloud request with id 2016 with method get_prop timed out after 30 seconds. MQTT connection state: true
[iobroker.2025-01-03.log.gz](https://github.com/user-attachments/files/18307077/iobroker.2025-01-03.log.gz)

Grüße
