### ISSUE TITLE
[BUG] Failed to get home details

### ISSUE THREAD

**Issue by Croxxii** [copystring/ioBroker.roborock#737]
### Bug Description

Hallo,

nach dem Adapter Start dauert es einige Zeit und dann kommt dieser Fehler. Wie im Screenshot zu sehen, tritt der Fehler exakt alle 3 Stunden auf! 

![18-12-_2024_16-09-51](https://github.com/user-attachments/assets/c309bfcf-d7d2-4fc4-bdaf-add409abe46b)

### Steps to Reproduce

Adapter starten und nach einiger Zeit kommt der Fehler

### Expected Behavior

No Error

### Debug Log

[debuglog.txt](https://github.com/user-attachments/files/18187995/debuglog.txt)

### Adapter Version

0.6.18

### JS-Controller Version

7.0.3

### Node.js Version

v20.18.0

### Operating System

Synology DSM 7.2.2-72806 Update 2 (Linux)

**Comment by Sandweier** [comment]
Same! Roborock S8. Adapterversion 0.6.18. Hint: In the past this error was not visible.

[iobroker.2024-12-19.log](https://github.com/user-attachments/files/18194950/iobroker.2024-12-19.log)

**Comment by copystring** [comment]
Please test https://github.com/copystring/ioBroker.roborock/tree/dev for 4–5 days. It should be fixed, but testing takes a while because this error my only appear after a few days.

**Comment by Croxxii** [comment]
Danke, ich habe mir die Version installiert und gebe nach ein paar Tagen Feedback

**Comment by Croxxii** [comment]
First of all Frohe Weihnachten und schöne Feiertage :)

Hier das gwünschte Feedback:

Ab und zu nach Adapter Neustart, kommen diese Fehlermeldungen. Aber kommt nicht bei jedem Adapter Neustart!

![Screenshot 2024-12-25 at 12-45-25 logs - iobroker-v10 0 0](https://github.com/user-attachments/assets/4c3a2105-bb0a-4eb9-96cd-5eaf7684c307)

Wenn der Adapter läuft, kommen dann Sekündlich diese Fehlermeldungen

![25-12-_2024_12-46-50](https://github.com/user-attachments/assets/33738994-fc12-4785-885f-d5ac6229e414)

Hier das Debuglog:
[debuglog.txt](https://github.com/user-attachments/files/18245796/debuglog.txt)

**Comment by Wolfi913** [comment]
Hatte heute mit der aktuellen dev-Version den selben Fehler alle Stunde. Der Fehler ist ohne Neustart aufgetreten. 
`2024-12-31 04:18:01.234 - error: roborock.0 (74804) startStopIntervals TypeError: this.vacuums[duid].getStatusIntervall is not a function`
42x innerhalb weniger ms
`2024-12-31 04:18:01.912 - error: roborock.0 (74804) startStopIntervals TypeError: this.vacuums[duid].getStatusIntervall is not a function`
Dann etwa 1h Pause. Anschließend
`2024-12-31 05:18:01.267 - error: roborock.0 (74804) startStopIntervals TypeError: this.vacuums[duid].getStatusIntervall is not a function`
... 38x ...
`2024-12-31 05:18:01.812 - error: roborock.0 (74804) startStopIntervals TypeError: this.vacuums[duid].getStatusIntervall is not a function`
Anschließend wieder ca. 1h keine Meldung bis
`2024-12-31 06:18:01.467 - error: roborock.0 (74804) startStopIntervals TypeError: this.vacuums[duid].getStatusIntervall is not a function`
... 26x ...
`2024-12-31 06:18:02.024 - error: roborock.0 (74804) startStopIntervals TypeError: this.vacuums[duid].getStatusIntervall is not a function`
1h keine Meldung
`2024-12-31 07:18:00.545 - error: roborock.0 (74804) startStopIntervals TypeError: this.vacuums[duid].getStatusIntervall is not a function`
... 38x ...
`2024-12-31 07:18:01.191 - error: roborock.0 (74804) startStopIntervals TypeError: this.vacuums[duid].getStatusIntervall is not a function`
Nach dem Restart des Adapters ist der Fehler bisher nicht mehr aufgetreten.

OT: Die `roborock.0.Devices.xxx.cleaningInfo.JSON` und somit die Historie wird bei mir z.T. nur nach Neustart des Adapters aktualisiert. Nicht nach jeder Fahrt des Geräts.

**Comment by Croxxii** [comment]
Gibt es hier schon News?

**Comment by copystring** [comment]
Vorletztes Wochenende konnte schon etwas machen, bin aber nicht fertig geworden. Der nächste Release soll aber den fix beinhalten.
Dauert nur noch ein bisschen. Habe leider nicht jedes Wochenende Zeit mich darum zu kümmern.

**Comment by pandel** [comment]
Nur zur Info: gleiches Fehlverhalten beim Qrevo Curv (ist das überhaupt modellabhängig?)

**Comment by copystring** [comment]
Versucht mal Version 0.6.19 aus der latest repo.

**Comment by Wolfi913** [comment]
Funktioniert bei mir leider nicht. Da stürzt der Adapter nach kurzer Zeit ab.

- 2025-02-08 23:44:29.690 - error: roborock.0 (3842) Cannot read properties of undefined (reading 'productId')
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[0]: TypeError: Cannot read properties of undefined (reading 'productId')
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[0]: at http_api.getRobotModel (/opt/iobroker/node_modules/iobroker.roborock/lib/http_api.js:227:66)
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[0]: at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:871:43)
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[0]: at requests_handler.sendRequest (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:712:17)
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[0]: at requests_handler.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:559:17)
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[1]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'productId')
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[1]: at http_api.getRobotModel (/opt/iobroker/node_modules/iobroker.roborock/lib/http_api.js:227:66)
- 2025-02-08 23:44:30.168 - error: host.iobroker-test Caught by controller[1]: at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:871:43)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[1]: at requests_handler.sendRequest (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:712:17)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[1]: at runNextTicks (node:internal/process/task_queues:60:5)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[1]: at processImmediate (node:internal/timers:454:9)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[1]: at requests_handler.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:562:26)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[2]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[2]: TypeError: Cannot read properties of undefined (reading 'productId')
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[2]: at http_api.getRobotModel (/opt/iobroker/node_modules/iobroker.roborock/lib/http_api.js:227:66)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[2]: at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:871:43)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[2]: at requests_handler.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:601:18)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[2]: at runNextTicks (node:internal/process/task_queues:60:5)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test Caught by controller[2]: at processImmediate (node:internal/timers:454:9)
- 2025-02-08 23:44:30.169 - error: host.iobroker-test instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by copystring** [comment]
Ok. Kümmere ich mich vielleicht morgen drum wenn ich Zeit finde.

**Comment by Wolfi913** [comment]
[debug_log.txt](https://github.com/user-attachments/files/18722501/debug_log.txt)

Falls es Dir hilft anbei ein hoffentlich vollständiges Debug-Log

**Comment by JackDaniel007** [comment]
das kommt jetzt im minutentakt :(

roborock.0 | 2025-02-09 07:49:13.509 | error | Failed to process get_status on robot 2t7w2Fu7NQgiuZTRbEgxWa (roborock.vacuum.a75): TypeError: Cannot read properties of undefined (reading 'dss') at requests_handler.getDockingStationStatus (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:184:50) at requests_handler.getParameter (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:252:43) at requests_handler.getStatus (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:114:4) at /opt/iobroker/node_modules/iobroker.roborock/main.js:104:8

roborock.0 | 2025-02-09 07:48:13.457 | error | Failed to process get_status on robot 2t7w2Fu7NQgiuZTRbEgxWa (roborock.vacuum.a75): TypeError: Cannot read properties of undefined (reading 'dss') at requests_handler.getDockingStationStatus (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:184:50) at requests_handler.getParameter (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:252:43) at requests_handler.getStatus (/opt/iobroker/node_modules/iobroker.roborock/lib/requests_handler.js:114:4) at /opt/iobroker/node_modules/iobroker.roborock/main.js:104:8

**Comment by Sandweier** [comment]
Same issue on my side.!!!
Workaround, feel free:Move back to 0.6.17. and wait until bug is fixed.
I did it and can so far live with it.

**Comment by copystring** [comment]
Wenn möglich bitte https://github.com/copystring/ioBroker.roborock/tree/dev testen und eine Rückmeldung geben. Danke!

**Comment by Wolfi913** [comment]
Schaut im ersten Moment bei mir gut aus. 
Gerät lässt sich auch über den Adapter steuren.
Hab aber noch zwei Warnings von meinem QRevo Slim

2025-02-10 00:53:31.228 - warn: roborock.0 (9342) State "roborock.0.Devices.6si...oaO.deviceStatus.carpet_mode" has no existing object, this might lead to an error in future versions
2025-02-10 00:53:31.236 - warn: roborock.0 (9342) State "roborock.0.Devices.6si...oaO.deviceStatus.carpet_clean_mode" has no existing object, this might lead to an error in future versions

**Comment by copystring** [comment]
In der neuen dev https://github.com/copystring/ioBroker.roborock/tree/dev ist ab sofort `carpet_mode` für den Qrevo slim eingebaut. Kommt dann im neuen Release. Möchtest du es vorher testen?

@Croxxii läuft bei dir die dev auch?

**Comment by Croxxii** [comment]
Ich werde es morgen unter Tags testen und gebe dann feedback.

**Comment by Wolfi913** [comment]
Hab die dev-Version gleich installiert. Bei mir tauchen jetzt keine Warnungen mehr auf.
Vielen Dank.

**Comment by copystring** [comment]
> Nachtrag: Eins ist mir noch aufgefallen. Die Daten im Zweig roborock.0.Devices.xxx.cleaningInfo werden bei mir (bei mehreren Tests mit Raumreinigung, jeweils immer einzelne Räume gestartet) nur beim Neustart des Adapters und nicht nach jedem gereinigten Raum aktualisiert.

@Wolfi913 in der neuen dev von gerade eben ist ein Auslöser eingebaut, welcher erkennt ob der Status von Saugroboter sich zu Aufladen geändert hat. Wenn der Saugroboter also in der Station zum Aufladen parkt oder man ihn selbst in die Station zum Aufladen stellt, wird `getCleanSummary` ausgeführt. Dadurch wird der Reinigungsverlauf komplett neu geholt.

**Comment by Wolfi913** [comment]
Hab ich gleich getestet. Funktioniert alles tadellos. In dem Moment in dem das Gerät auf `Charging` geht wird aktualisiert.
Herzlichsten Dank.

**Comment by Croxxii** [comment]
@copystring Der Adapter schnurrt wie ein Kätzchen :) Keine Fehlermeldungen bisher!
