### ISSUE TITLE
[BUG] Failed to get home details: Error: Not running at healthCheck

### ISSUE THREAD

**Issue by V-Pixel1** [copystring/ioBroker.roborock#740]
### Bug Description

`Failed to get home details: Error: Not running at healthCheck (node:dgram:922:11) at Socket.bind (node:dgram:242:3) at /opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:213:11 at new Promise (<anonymous>) at localConnector.getLocalDevices (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:185:10) at Roborock.initializeHomeDetails (/opt/iobroker/node_modules/iobroker.roborock/main.js:197:56) at /opt/iobroker/node_modules/iobroker.roborock/main.js:77:4`

Erscheint seit neuestem im ioBroker Log.

### Steps to Reproduce

Erscheint sporadisch

### Expected Behavior

Kein Fehler erwartet.

### Debug Log

`Failed to get home details: Error: Not running at healthCheck (node:dgram:922:11) at Socket.bind (node:dgram:242:3) at /opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:213:11 at new Promise (<anonymous>) at localConnector.getLocalDevices (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:185:10) at Roborock.initializeHomeDetails (/opt/iobroker/node_modules/iobroker.roborock/main.js:197:56) at /opt/iobroker/node_modules/iobroker.roborock/main.js:77:4`

### Adapter Version

v0.6.18

### JS-Controller Version

7.0.3

### Node.js Version

v20.18.1

### Operating System

Raspbian

**Comment by V-Pixel1** [comment]
Issue doppelt.
